### ISSUE TITLE
One blank character too much

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#304] opened 2017-08-17 17:19 UTC
Just a minor issue:
![2017-08-17-190851_1920x1080_scrot](https://user-images.githubusercontent.com/8258609/29424637-c19311ca-8380-11e7-96f6-b369d9e29cb0.png)

Instead of
`Ich␣: ...` it should be `Ich: ...`

It's in the chat list. Would have fixed it but I could not find where it is defined.

**Comment by dbrgn** [comment] 2017-08-17 21:28
Ah, that might actually be defined via CSS `:after` text.

**Comment by sillych** [comment] 2017-09-12 07:47
Nope, the `:after` tag only define a space after the colon. The problem is the newline and spaces in the HTML. Fixed in #338

**Closed** 2017-09-12 07:47 UTC
Labels: bug, ui
