### ISSUE TITLE
Show download button for images not already downloaded

### ISSUE THREAD

**Issue by xan-a-a** [threema-ch/threema-web#780] opened 2019-03-21 13:15 UTC
In a group chat, 3 images didn't display on Threema Web. Just "empty" messages. In the iPhone app, those were marked with a clickable "Image" icon. Once clicked, they also appeared in Threema Web.

![image](https://user-images.githubusercontent.com/46072148/54754383-ab977500-4be3-11e9-9f5d-329798aac818.png)

**Comment by xan-a-a** [comment] 2019-03-21 13:17
I still have 2 "pictures" like that. If there is something you need me to do to debug this please let me know.

**Comment by lgrahl** [comment] 2019-03-21 14:19
This happens when the app has not yet downloaded the image or it has deactivated that (e.g. for cellular networks). We need to show a *download button* in such a case.

**Comment by xan-a-a** [comment] 2019-03-21 14:20
Ok thank you, I understand but just FYI I wasn't on cellular so it's probably caused by something else.

**Comment by lgrahl** [comment] 2019-03-21 14:22
In that case, contact `*SUPPORT` since that is a matter of the app. :slightly_smiling_face:

**Comment by lgrahl** [comment] 2019-05-03 17:02
Duplicate of #485

**Closed by lgrahl** 2019-05-03 17:02 UTC
Labels: bug, ui
