### ISSUE TITLE
Web client duplicates typed messages, sending them twice

### ISSUE THREAD

**Issue by leeps** [threema-ch/threema-web#481] opened 2018-03-30 09:39 UTC
## Expected Behavior
If I type and send a single message, it should be sent only once

## Current Behavior
Messages entered into the web client get duplicated and are send twice. Does not matter if group or direct message.
I have attached screenshots of a conversation with *ECHOECHO*.

**Test cases:**
Messages get duplicated when sent by pressing return/enter ("test") or by clicking on the send/play icon next to the text entry field ("test2"). Messages do _not_ get duplicated when sent on my phone, even if web client is connected ("Test 3").
![3maweb1](https://user-images.githubusercontent.com/1220195/38132914-4ed1925e-340d-11e8-9b98-d48d67bca05f.png)

CTRL+F5 reloading does not help ("test4"), neither does restarting the browser (not covered in screenshots, sorry!).
*Deleting the web session and recreating it helps* ("test5").
![3maweb2](https://user-images.githubusercontent.com/1220195/38132916-4f11312a-340d-11e8-82b0-abb3435b3c22.png)

*Edit:*
I remembered just now what might be an important detail:
Immediately after the message is sent, it is first shown in the chat only once, in sending state (arrow pointing up). Only after successful being sent (it seems, state changes so fast) it is shown twice.

After recreating the web session, the issue shows up again after a while (varying amounts of time). It is currently the third time it has happened, prompting me to open this issue.
The app does have a second web session (at work) with Chrome on Linux, which as never shown this issue.
The first time it happened on my home desktop I actually went to work without recreating the web session. Using the work web session the issue was gone, but returning to the home session it was still there.

## Possible Solution
- no idea at all
- i have a background in web developement and am willing to help debug this. I can use a javascript debugger, but don't know what to look for.

## Steps to Reproduce (for bugs)
- no idea what triggers it

## Your Environment
* Threema Web version: 1.8.2
* Threema for Android version: 3.41.413 Threema Shop
* Threema for Android source: Threema Store
* Browser name and version: Chromium Version 64.0.3282.186 (Developer Build) (64-bit)
* Operating system and version: Linux on desktop, Android 6.0.1 on Phone

**Comment by dbrgn** [comment] 2018-03-30 12:44
I've also experienced this in the past. It must be a bug in the Android app (listeners getting registered twice).

**Comment by leeps** [comment] 2018-03-30 13:36
@dbrgn That would suggest that there is nothing I could do to help debugging this, as I cannot see inside the app.
I will try to confirm by restarting the app the next time it happens.

Let me know if you think I could provide you with more data or information.

**Comment by dbrgn** [comment] 2018-03-30 13:39
@leeps unfortunately you are right. We'll try to track down the issue in the future.

If you restart the app, make sure to completely stop it (via settings -> apps), swiping it away in the "open apps" drawer will probably not terminate the background process.

**Comment by leeps** [comment] 2018-03-30 13:41
I'll make sure to "force stop" the app.

**Comment by lgrahl** [comment] 2018-09-24 21:27
I haven't encountered this in a while. Is it still an issue?

**Comment by dbrgn** [comment] 2018-10-03 07:41
Closing due to inactivity. Since we did a lot of refactoring, I suspect this issue was fixed.

**Comment by jaltek** [comment] 2018-10-22 13:51
Just for the record: This issue happened to me today as well. "Force stop" via settings fixed it.

**Comment by dbrgn** [comment] 2018-10-24 15:34
@jaltek version 2.1.0 was released yesterday. Can you test with that?

If it happens again with the current version, we can re-open.

**Comment by rugk** [comment] 2018-10-25 06:59
Is v2.1.0 still a pre-release with no ZIP on GitHub? Basically, you did not create a new release on GitHub, so I always consider these pre-releases.

**Comment by jaltek** [comment] 2018-10-25 07:00
> @jaltek version 2.1.0 was released yesterday. Can you test with that?
> 
> If it happens again with the current version, we can re-open.

I'll keep an eye on it. As already mentioned it is difficult to reproduce.

**Comment by dbrgn** [comment] 2018-10-25 07:09
> Is v2.1.0 still a pre-release with no ZIP on GitHub?  Basically, you did not create a new release on GitHub, so I always  consider these pre-releases.

Published now, sorry for the delay.

**Comment by dbrgn** [comment] 2018-10-30 21:38
Doesn't seem to be fixed, see #660.

**Comment by rugk** [comment] 2018-10-30 22:25
Here is a console log of Threema Web for sending such a (one!) duplicate message to ECHOECHO:

```
Sending update/typing message angular.js:15535:16
Sending create/textMessage message angular.js:15535:16
New incoming message (114 bytes) angular.js:15535:16
Received create/textMessage message angular.js:15535:16
Received create message response angular.js:15535:16
New incoming message (350 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (263 bytes) angular.js:15535:16
Received update/messages message angular.js:15535:16
Received messages update angular.js:15535:16
New incoming message (350 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (268 bytes) angular.js:15535:16
Received update/messages message angular.js:15535:16
Received messages update angular.js:15535:16
New incoming message (336 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (241 bytes) angular.js:15535:16
Received update/messages message angular.js:15535:16
Received messages update angular.js:15535:16
New incoming message (336 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (268 bytes) angular.js:15535:16
Received update/messages message angular.js:15535:16
Received messages update angular.js:15535:16
New incoming message (336 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (268 bytes) angular.js:15535:16
Received update/messages message angular.js:15535:16
Received messages update angular.js:15535:16
New incoming message (336 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (268 bytes) angular.js:15535:16
Received update/messages message angular.js:15535:16
Received messages update angular.js:15535:16
New incoming message (336 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (227 bytes) angular.js:15535:16
Received update/messages message angular.js:15535:16
Received messages update angular.js:15535:16
New incoming message (336 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (268 bytes) angular.js:15535:16
Received update/messages message angular.js:15535:16
Received messages update angular.js:15535:16
New incoming message (336 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (268 bytes) angular.js:15535:16
Received update/messages message angular.js:15535:16
Received messages update angular.js:15535:16
New incoming message (336 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (227 bytes) angular.js:15535:16
Received update/messages message angular.js:15535:16
Received messages update angular.js:15535:16
Sending read request for contact ECHOECHO (msg 27647) angular.js:15535:16
Sending request/read message angular.js:15535:16
New incoming message (336 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (336 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (383 bytes) angular.js:15535:16
Received update/messages message angular.js:15535:16
Received messages update angular.js:15535:16
New incoming message (62 bytes) angular.js:15535:16
Received update/batteryStatus message angular.js:15535:16
Received battery status angular.js:15535:16
[BatteryStatusService] 55%, charging angular.js:15535:16 
```

**Comment by rugk** [comment] 2018-10-30 22:51
Okay, other try.

Message log:

```
Tue Oct 30 23:34:18 GMT+01:00 2018	releaseConnectionLinger: source = activityPaused, timeout = 60000
Tue Oct 30 23:34:18 GMT+01:00 2018	Cancel alarm type 1
Tue Oct 30 23:34:18 GMT+01:00 2018	Schedule alarm type 1 in 59996ms
Tue Oct 30 23:34:18 GMT+01:00 2018	acquireConnection: source = activityResumed, refCount = 1
Tue Oct 30 23:34:18 GMT+01:00 2018	another connection is already active
Tue Oct 30 23:34:30 GMT+01:00 2018	acquireConnection: source = wc.createMessage, refCount = 2
Tue Oct 30 23:34:30 GMT+01:00 2018	another connection is already active
Tue Oct 30 23:34:30 GMT+01:00 2018	sendTextMessage: start
Tue Oct 30 23:34:30 GMT+01:00 2018	Enqueue text message ID b52304bfcd3a9342 to ECHOECHO
Tue Oct 30 23:34:30 GMT+01:00 2018	outgoing message ID b52304bfcd3a9342 from MYTHREEMAID to ECHOECHO
Tue Oct 30 23:34:30 GMT+01:00 2018	Nonce: c4ba5e54bd967608576b364b6082910613a9cc4be364f4d2
Tue Oct 30 23:34:30 GMT+01:00 2018	Data: f89ced3dc2a31aff1f3e4fbf3818db17663ae89e1d6425853aec16d338cf40802ade7ede36c07df99b71e67a50999e781ad1edbc8f83257c145e4bafb7ff4a5d044992ae5b367df41159d3b636be
Tue Oct 30 23:34:30 GMT+01:00 2018	Public key (ECHOECHO): 4a6a1b34dcef15d43cb74de2fd36091be99fbbaf126d099d47d83d919712c72b
Tue Oct 30 23:34:30 GMT+01:00 2018	message b52304bfcd3a9342 successfully queued
Tue Oct 30 23:34:30 GMT+01:00 2018	process ACK for message b52304bfcd3a9342
Tue Oct 30 23:34:31 GMT+01:00 2018	Incoming message ID 0a8bcef3c1bea952 from ECHOECHO to MYTHREEMAID
Tue Oct 30 23:34:31 GMT+01:00 2018	releaseConnectionLinger: source = wc.createMessage, timeout = 5000
Tue Oct 30 23:34:31 GMT+01:00 2018	acquireConnection: source = wc.createMessage, refCount = 2
Tue Oct 30 23:34:31 GMT+01:00 2018	another connection is already active
Tue Oct 30 23:34:31 GMT+01:00 2018	sendTextMessage: start
Tue Oct 30 23:34:31 GMT+01:00 2018	Message 0a8bcef3c1bea952: type 0x80
Tue Oct 30 23:34:31 GMT+01:00 2018	Message 0a8bcef3c1bea952: delivery receipt for b52304bfcd3a9342 (state = READ)
Tue Oct 30 23:34:31 GMT+01:00 2018	Enqueue text message ID 433bb8309fad0922 to ECHOECHO
Tue Oct 30 23:34:31 GMT+01:00 2018	Incoming message ID 087489bd1ca1c6b3 from ECHOECHO to MYTHREEMAID
Tue Oct 30 23:34:31 GMT+01:00 2018	outgoing message ID 433bb8309fad0922 from MYTHREEMAID to ECHOECHO
Tue Oct 30 23:34:31 GMT+01:00 2018	Nonce: 4dc7acbbac18c0108342a225aa2bf197f69f133cb488d7d9
Tue Oct 30 23:34:31 GMT+01:00 2018	Data: 77475a796b4c707ff49b11e3ee6708eb3650645a1136e21098cabc0ec422d3a9abcc3988e7d1b4ffb8227fb2d6a9aee5686c7ba0ab0cada8a99f21d7a8001a43d36caad8153fef7a305d878c6b0a81
Tue Oct 30 23:34:31 GMT+01:00 2018	Public key (ECHOECHO): 4a6a1b34dcef15d43cb74de2fd36091be99fbbaf126d099d47d83d919712c72b
Tue Oct 30 23:34:31 GMT+01:00 2018	message 433bb8309fad0922 successfully queued
Tue Oct 30 23:34:31 GMT+01:00 2018	Nonce: 000f939c5fbb300f5f41b33b8152235111eab774f0150873
Tue Oct 30 23:34:31 GMT+01:00 2018	Data: 7b2eb8ae84bc24778322f840911df56e9cacff1bf9b51c5f079e5af9b1f8615b958ebd258e791e88a1f5a05fc54acd3e0ebcb59f62c6cb2d31c097482bc4b0239e2d9550b566b16b8e5089f30a53
Tue Oct 30 23:34:31 GMT+01:00 2018	Public key (ECHOECHO): 4a6a1b34dcef15d43cb74de2fd36091be99fbbaf126d099d47d83d919712c72b
Tue Oct 30 23:34:31 GMT+01:00 2018	Message 087489bd1ca1c6b3: type 0x1
Tue Oct 30 23:34:31 GMT+01:00 2018	Abstract Message 087489bd1ca1c6b3: type 0x1
Tue Oct 30 23:34:31 GMT+01:00 2018	processIncomingContactMessage: 087489bd1ca1c6b3
Tue Oct 30 23:34:31 GMT+01:00 2018	processIncomingContactMessage: 087489bd1ca1c6b3 - A
Tue Oct 30 23:34:31 GMT+01:00 2018	releaseConnectionLinger: source = wc.createMessage, timeout = 5000
Tue Oct 30 23:34:31 GMT+01:00 2018	Showing notification for message 087489bd1ca1c6b3
Tue Oct 30 23:34:31 GMT+01:00 2018	Showing notification 08fa1cf0-5a18-4405-88dd-dea36027b4e2 sound: content://settings/system/notification_sound
Tue Oct 30 23:34:31 GMT+01:00 2018	Enqueue delivery receipt (delivered) message ID 9948df636cdcf7ae for message ID 087489bd1ca1c6b3 from ECHOECHO
Tue Oct 30 23:34:31 GMT+01:00 2018	process ACK for message 433bb8309fad0922
Tue Oct 30 23:34:31 GMT+01:00 2018	acquireConnection: source = WebclientMessageDispatcher, refCount = 2
Tue Oct 30 23:34:31 GMT+01:00 2018	another connection is already active
Tue Oct 30 23:34:31 GMT+01:00 2018	releaseConnectionLinger: source = WebclientMessageDispatcher, timeout = 5200
Tue Oct 30 23:34:31 GMT+01:00 2018	acquireConnection: source = WebclientMessageDispatcher, refCount = 2
Tue Oct 30 23:34:31 GMT+01:00 2018	another connection is already active
Tue Oct 30 23:34:31 GMT+01:00 2018	releaseConnectionLinger: source = WebclientMessageDispatcher, timeout = 5100
Tue Oct 30 23:34:31 GMT+01:00 2018	Incoming message ID b9d893624af6e3bb from ECHOECHO to MYTHREEMAID
Tue Oct 30 23:34:31 GMT+01:00 2018	Message b9d893624af6e3bb: type 0x80
Tue Oct 30 23:34:31 GMT+01:00 2018	Message b9d893624af6e3bb: delivery receipt for 433bb8309fad0922 (state = READ)
Tue Oct 30 23:34:31 GMT+01:00 2018	Incoming message ID 7d8b0b3fde2e222f from ECHOECHO to MYTHREEMAID
Tue Oct 30 23:34:31 GMT+01:00 2018	Nonce: 5b0a4f7c877c5fc677b312f773987534a9abda22188cc1b1
Tue Oct 30 23:34:31 GMT+01:00 2018	Data: 464e8356fe00db1ff326c43961bc93c7ecece7c10acca02a1c9da2bf09c3ddd01303a67af0ca9f33cbea66b4d5bb4cd01569df898cf269346da2a99f979ba76b833dd3ee0b6070d8f600765e2e1d4b
Tue Oct 30 23:34:31 GMT+01:00 2018	Public key (ECHOECHO): 4a6a1b34dcef15d43cb74de2fd36091be99fbbaf126d099d47d83d919712c72b
Tue Oct 30 23:34:31 GMT+01:00 2018	Message 7d8b0b3fde2e222f: type 0x1
Tue Oct 30 23:34:31 GMT+01:00 2018	Abstract Message 7d8b0b3fde2e222f: type 0x1
Tue Oct 30 23:34:31 GMT+01:00 2018	processIncomingContactMessage: 7d8b0b3fde2e222f
Tue Oct 30 23:34:31 GMT+01:00 2018	processIncomingContactMessage: 7d8b0b3fde2e222f - A
Tue Oct 30 23:34:31 GMT+01:00 2018	Showing notification for message 7d8b0b3fde2e222f
Tue Oct 30 23:34:31 GMT+01:00 2018	Showing notification fbf68256-a603-4425-ab26-b2e39c9f5315 sound: null
Tue Oct 30 23:34:31 GMT+01:00 2018	Enqueue delivery receipt (delivered) message ID c9d92dd2b9f39f90 for message ID 7d8b0b3fde2e222f from ECHOECHO
Tue Oct 30 23:34:32 GMT+01:00 2018	process ACK for message 9948df636cdcf7ae
Tue Oct 30 23:34:32 GMT+01:00 2018	process ACK for message c9d92dd2b9f39f90
Tue Oct 30 23:34:36 GMT+01:00 2018	Enqueue delivery receipt (read) message ID 454caaef0230bad3 for message ID 7d8b0b3fde2e222f from ECHOECHO
Tue Oct 30 23:34:36 GMT+01:00 2018	process ACK for message 454caaef0230bad3
Tue Oct 30 23:34:36 GMT+01:00 2018	Enqueue delivery receipt (read) message ID 107706bd99d174cf for message ID 087489bd1ca1c6b3 from ECHOECHO
Tue Oct 30 23:34:36 GMT+01:00 2018	class adv: cancel conversation notification
Tue Oct 30 23:34:36 GMT+01:00 2018	acquireConnection: source = WebclientMessageDispatcher, refCount = 2
Tue Oct 30 23:34:36 GMT+01:00 2018	another connection is already active
Tue Oct 30 23:34:36 GMT+01:00 2018	releaseConnectionLinger: source = WebclientMessageDispatcher, timeout = 5100
Tue Oct 30 23:34:36 GMT+01:00 2018	acquireConnection: source = WebclientMessageDispatcher, refCount = 2
Tue Oct 30 23:34:36 GMT+01:00 2018	another connection is already active
Tue Oct 30 23:34:36 GMT+01:00 2018	releaseConnectionLinger: source = WebclientMessageDispatcher, timeout = 5100
Tue Oct 30 23:34:37 GMT+01:00 2018	process ACK for message 107706bd99d174cf
Tue Oct 30 23:34:42 GMT+01:00 2018	releaseConnectionLinger: source = activityPaused, timeout = 60000
Tue Oct 30 23:34:42 GMT+01:00 2018	Cancel alarm type 1
Tue Oct 30 23:34:43 GMT+01:00 2018	Schedule alarm type 1 in 59910ms
Tue Oct 30 23:35:42 GMT+01:00 2018	Alarm type 1 received
Tue Oct 30 23:35:43 GMT+01:00 2018	Handling alarm type 1
Tue Oct 30 23:35:43 GMT+01:00 2018	stopConnection
Tue Oct 30 23:35:43 GMT+01:00 2018	ThreemaConnection state changed: DISCONNECTED Port: 5222 IPv6: false
Tue Oct 30 23:35:43 GMT+01:00 2018	MessageServiceImpl: Queue saved. Size = 0
Tue Oct 30 23:35:43 GMT+01:00 2018	cleanupConnection: connection closed
Tue Oct 30 23:36:01 GMT+01:00 2018	Handling incoming GCM intent.
Tue Oct 30 23:36:01 GMT+01:00 2018	Received GCM message: Bundle[{collapse_key=new_message}]
Tue Oct 30 23:36:01 GMT+01:00 2018	Fetch attempt. Source = gcm
Tue Oct 30 23:36:01 GMT+01:00 2018	PollingHelper: Aquiring wakelock
Tue Oct 30 23:36:01 GMT+01:00 2018	acquireConnection: source = gcm, refCount = 1
Tue Oct 30 23:36:01 GMT+01:00 2018	startConnection
Tue Oct 30 23:36:01 GMT+01:00 2018	Starting connection
```

web console:

``` 
Sending update/typing message angular.js:15535:16
Sending create/textMessage message angular.js:15535:16
Sending update/typing message angular.js:15535:16
New incoming message (114 bytes) angular.js:15535:16
Received create/textMessage message angular.js:15535:16
Received create message response angular.js:15535:16
New incoming message (349 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (262 bytes) angular.js:15535:16
Received update/messages message angular.js:15535:16
Received messages update angular.js:15535:16
New incoming message (335 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (335 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (267 bytes) angular.js:15535:16
Received update/messages message angular.js:15535:16
Received messages update angular.js:15535:16
New incoming message (267 bytes) angular.js:15535:16
Received update/messages message angular.js:15535:16
Received messages update angular.js:15535:16
New incoming message (335 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (262 bytes) angular.js:15535:16
Received update/messages message angular.js:15535:16
Received messages update angular.js:15535:16
New incoming message (335 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (267 bytes) angular.js:15535:16
Received update/messages message angular.js:15535:16
Received messages update angular.js:15535:16
New incoming message (335 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (267 bytes) angular.js:15535:16
Received update/messages message angular.js:15535:16
Received messages update angular.js:15535:16
New incoming message (335 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (226 bytes) angular.js:15535:16
Received update/messages message angular.js:15535:16
Received messages update angular.js:15535:16
New incoming message (335 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (267 bytes) angular.js:15535:16
Received update/messages message angular.js:15535:16
Received messages update angular.js:15535:16
New incoming message (335 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (267 bytes) angular.js:15535:16
Received update/messages message angular.js:15535:16
Received messages update angular.js:15535:16
New incoming message (335 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (226 bytes) angular.js:15535:16
Received update/messages message angular.js:15535:16
Received messages update angular.js:15535:16
Sending read request for contact ECHOECHO (msg 27651) angular.js:15535:16
Sending request/read message angular.js:15535:16
New incoming message (335 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (335 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (381 bytes) angular.js:15535:16
Received update/messages message angular.js:15535:16
Received messages update angular.js:15535:16
New incoming message (342 bytes) angular.js:15535:16
Received update/conversation message angular.js:15535:16
Received conversation update angular.js:15535:16
New incoming message (219 bytes) angular.js:15535:16
Received update/messages message angular.js:15535:16
Received messages update angular.js:15535:16
New incoming message (62 bytes) angular.js:15535:16
Received update/batteryStatus message angular.js:15535:16
Received battery status angular.js:15535:16
[BatteryStatusService] 57%, charging angular.js:15535:16
```

**Comment by ovalseven8** [comment] 2018-12-07 17:52
Not sure if I'm right here, but today I used the **Android app** and sent an image. It has been sent twice.

**Comment by rugk** [comment] 2018-12-07 18:08
FYI I could not reproduce this bug with the latest Threema Beta apps and v2.1.2 of Threema Web for quite some time. So for me it seems to be fixed…

**Comment by lgrahl** [comment] 2018-12-07 19:16
I'll close this for now. Please let us know in case it happens again (in the web client).

@ovalseven8 not really - you probably want to contact `*SUPPORT` for that. :slightly_smiling_face:

**Closed by lgrahl** 2018-12-07 19:16 UTC
Labels: app-update, awaiting feedback, bug
