### ISSUE TITLE
Sent images not shown

### ISSUE THREAD

**Issue by oliver-graetz** [threema-ch/threema-web#36] opened 2017-02-15 22:01 UTC
When I drag an image file (PNG file in this case) onto a chat in Threema Web (a group chat in this case), it is sent to the chat and I can see it in the same chat on the phone, but it isn't shown inside Threema Web. There is just an empty message or just the caption for the image. Threema Web is used on Chrome 56.

**Comment by rugk** [comment] 2017-02-15 22:05
dupe of https://github.com/threema-ch/threema-web/issues/29

**Comment by oliver-graetz** [comment] 2017-02-15 23:12
Oh sorry. From what I read I thought that the other issue was about the UI when uploading the file (i.e. not shwoing some kind of preview before uploading), and not about the result.

**Closed** 2017-02-16 08:33 UTC
Labels: duplicate
