### ISSUE TITLE
Interactive graphic that shows anonymity and encryption using Threema

### ISSUE THREAD

**Issue by dwaal** [threema-ch/threema-web#526] opened 2018-07-19 12:08 UTC
Hi,

the FAQ are good but an interactive graphic like this for Threema would really help: https://www.eff.org/pages/tor-and-https

**Comment by dbrgn** [comment] 2018-07-19 12:20
Thanks for the suggestion. Probably related to #13?

**Comment by rugk** [comment] 2018-07-19 14:12
I'd also even say it is a dupe of https://github.com/threema-ch/threema-web/issues/13, the interactive thing with more details may be mentioned in some doc. Or well... maybe not.

**Comment by dwaal** [comment] 2018-07-19 14:34
My suggestion is not specific to 'Threema Web'. I just wish there were simple graphics available (as part of the FAQ or as help guides in the Threema app and Threema Web).

Each graphic should explain just a single process, e.g.

1. the communication between the Android app and Threema Web (visualize how IP, data, etc. is visible to your ISP, hackers, etc.)

2. app to app communication (again visualizing IPs, data, etc.)

3. contact list syncronization (what data is submitted, etc.)

4. purchasing the app. Is the mode of payment (which can be used to identify a user) or connection to the Play Store in any way tied to the users Threema-ID or anything else that may identify the user.

5. ...

The textual explanations are as good as can be. Still, most people can grasp the situation much more easily using simple graphics to intuitively visualize the android app, the Threema servers, other people they talk to and the IPs and data flowing between them.

**Comment by lgrahl** [comment] 2018-07-19 15:44
Something like this?

![image](https://user-images.githubusercontent.com/1793755/42953312-7370a43c-8b7a-11e8-9bef-6947727ecd40.png)

From my [thesis](https://lgrahl.de/articles/ba-thesis-saltyrtc.html) (not entirely accurate any more):

> 1. First of all, the browser creates a SaltyRTC instance which automatically generates a new permanent key pair. The browser requests an authentication token and displays the hex encoded token in a QR code.
> 2. In the app, the user has to start the Web Client. A SaltyRTC instance starts and a new permanent key pair will be generated. The app will show a camera preview and the user has to scan the QR code with the smartphone camera.
> 3. Both browser and app connect to the same signalling server and use the permanent public key of the browser as the path value.
> 4. The app uses the secret key provided in the authentication token to authenticate itself towards the browser.
> 5. To establish the peer connection, the browser sends the offer message and the app responds with an answer message. Afterwards, ICE candidates will be exchanged.
> 6. The peer-to-peer connection is being established and the browser creates a data channel with the label `3ema`. The app receives information about the newly created data channel and waits for incoming messages.
> 7. Now, the browser requests various initial data, e.g. the contact list, a list of conversations, the avatar images, etc. and the app sends the requested data back to the browser. The browser will receive updates to requested data and can request additional data from the app.

**Comment by dwaal** [comment] 2018-07-19 17:08
Yes, something like this, just with less detail in the style of this: (scroll down, press buttons: HTTPS and Tor) https://www.eff.org/pages/tor-and-https

The technical details are not really important. More important is to show the various ways the data and metadata/IPs is flowing and who has access where and to what extend.

**Comment by ovalseven8** [comment] 2018-07-19 17:39
Just out of interest, may I ask which program you used for the graphic, @lgrahl? :)

**Comment by lgrahl** [comment] 2018-07-19 18:41
The magnificent https://www.draw.io/

**Comment by dbrgn** [comment] 2018-07-19 20:10
@dwaal I have forwarded your idea to the responsible person. Thanks for the suggestion. I will close this issue, since it does not have anything to do with the Threema Web software itself.

**Closed by dbrgn** 2018-07-19 20:10 UTC
