### ISSUE TITLE
Feature: message forwarding

### ISSUE THREAD

**Issue by merlin2004** [threema-ch/threema-web#55] opened 2017-02-16 18:18 UTC
We can simple forward a message or picture in the native Android/IOS app.
Is there a plan to implement this feature in the web client?

**Comment by rugk** [comment] 2017-02-16 18:19
Please use the search before opening an issue. This is a dupe of https://github.com/threema-ch/threema-web/issues/3.

**Comment by merlin2004** [comment] 2017-02-16 18:31
Sorry

**Closed** 2017-02-16 18:30 UTC
Labels: duplicate
