### ISSUE TITLE
Images not downloaded are neither visible nor requestable

### ISSUE THREAD

**Issue by lgrahl** [threema-ch/threema-web#523] opened 2018-07-10 19:35 UTC
## Expected Behavior

Display a message with an image placeholder and allow to request to download and display the image.

## Current Behavior

Images that have not already been downloaded are displayed within an empty message and cannot be requested to be downloaded.

![image](https://user-images.githubusercontent.com/1793755/42533045-0737e0f2-8489-11e8-81ac-c18a5aab2cf7.png)

## Steps to Reproduce (for bugs)

1. Turn off automatic image downloading.
2. Receive an image message.
3. Open the conversation in the Web Client.

**Comment by rugk** [comment] 2018-07-10 19:39
Duplicate of https://github.com/threema-ch/threema-web/issues/485(?)

**Comment by lgrahl** [comment] 2018-07-10 20:01
We can close either. I let you decide which one. :wink:

**Comment by rugk** [comment] 2018-07-10 20:09
Well… the usual way is to close the new issues as dupes of old ones.
But I'll better let @dbrgn or so decide what to close. :smile:

**Comment by dbrgn** [comment] 2018-07-10 22:09
Closing in favor of #485.

**Comment by rugk** [comment] 2018-07-11 06:35
The thing is just that this issue here is not closed though. 😆

**Closed** 2018-07-11 07:34 UTC
Labels: bug
