### ISSUE TITLE
Pin/unpin conversation

### ISSUE THREAD

**Issue by lgrahl** [threema-ch/threema-web#595] opened 2018-09-25 13:24 UTC
The message handling is already implemented on the app side (both). Only UI stuff left.

**Comment by dbrgn** [comment] 2018-10-03 11:19
On Android only since 3.53, that's why the UI wasn't added yet. It's already mostly implemented in the `361-pin-chats` branch. I think by now most apps should be updated, I'll create a PR soon :slightly_smiling_face:

**Comment by dbrgn** [comment] 2018-10-04 09:00
Closing as duplicate of #361.

**Closed by dbrgn** 2018-10-04 09:00 UTC
Labels: easy, feature, ui
