### ISSUE TITLE
Cannot send .webm video in video format

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#115] opened 2017-02-28 21:16 UTC
## Expected Behavior
When sending a .webm file, it should be sent as normal video by default.

## Current Behavior
Cannot send a .webm file as a video, only as a file.

## Your Environment
* Threema Web version: 1.0.3
* Threema for Android version: 3.01
* Threema for Android source: Play Store
* Browser name and version: Firefox 51.0.1

**Comment by dbrgn** [comment] 2017-03-06 08:21
Isn't this a duplicate of #114?

**Closed by dbrgn** 2017-03-06 08:21 UTC

**Comment by ovalseven8** [comment] 2017-03-06 08:59
No, because in #114 there is the choice between sending as "video" and "file".
Here I don't even have the choice and can only send as file.

**Comment by dbrgn** [comment] 2017-03-06 09:37
I see. But they can both be summarized as "fix sending of videos" :)
