### ISSUE TITLE
Some contacts cannot receive images anymore

### ISSUE THREAD

**Issue by reneraab** [threema-ch/threema-web#739] opened 2019-01-28 12:44 UTC
## Expected Behavior
When trying to send a picture from Threema Web either to a contact directly or to a group, all contacts should receive the picture.

## Current Behavior
When sending a picture with Threema Web (either pasted or opened through the file picker), the error message "[contact] cannot receive this message." occurs. This only happens for some contacts and sending pictures to other contacts works as expected. Sending a picture to a group that contains an affected contact results in the same error message and the picture is not being sent to the group.

It is possible to send pictures to the affected contact through the app.

## Steps to Reproduce (for bugs)
1. Open a conversation in Threema Web
2. Paste or open a picture
3. Send the picture (with or without text)
4. Error message appears (for some contacts)

## Your Environment
* Threema Web version: 2.1.5
* Threema App version: 3.61 Build 465 Threema Shop
* Threema App version of affected contact: 4.1 (2423)
* Browser name and version: Firefox 64.0 (64-bit)
* Computer operating system and version: Linux Mint 19
* Smartphone operating system and version: LineageOS 15.1

**Comment by dbrgn** [comment] 2019-01-28 14:33
Unfortunately that's a long-standing issue that we thought we've fixed multiple times now, but it appears that it still hasn't been fully resolved :slightly_frowning_face:

Did you recently restore a backup?

Note that as a workaround, you should be able to send a picture to every affected contact directly through the app. Once that's done, reload Threema Web and now you should be able to send images to the group through Threema Web too.

**Comment by reneraab** [comment] 2019-01-28 14:54
Yes, I did restore a backup yesterday.

The proposed workaround does not work. I was able to send a picture to an affected contact through the app. However, I was not able to then send a picture to either that same contact or the group through Threema Web after reloading. (To make sure, I also tried it with a new Threema Web session)

**Comment by dbrgn** [comment] 2019-01-28 16:41
The error message lists the contacts where the so-called "feature mask" has not been updated properly. Is it still the same contact whom you sent an image through the app that is listed in the error message?

> Yes, I did restore a backup yesterday.

That's good to know. We made a fix to the app recently that should resolve the cause the issue in this case, but it's not released yet. It should be in the next app release though.

**Comment by reneraab** [comment] 2019-01-28 17:43
I tried to perform the workaround again. This time it seemed to have worked and I can now send images to the problematic contact via Threema Web again (both directly and in the group). And yes, I always sent images to the same contact.

Thank you for the workaround!

**Comment by ovalseven8** [comment] 2019-02-07 17:51
Is this fixed with the new version?

**Comment by dbrgn** [comment] 2019-02-11 15:53
Yes, the problem with outdated feature masks after restoring a backup should be fixed in 3.62.

**Closed by dbrgn** 2019-02-11 15:53 UTC
Labels: bug
