### ISSUE TITLE
Sometimes I cannot input anything

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#128] opened 2017-03-02 21:37 UTC
## Expected Behavior

Input as usual…

## Current Behavior

Sometimes when writing a lot (heavy discussion :wink:) I could not write into the input field and the cursor was somehow displaced to the bottom-left. No text appeared when typing…

A fix: Switch to another chat and switch back to the previous one…

## Steps to Reproduce (for bugs)

Write a lot…

## Your Environment

* Threema Web version: 1.0.4
* Browser name and version: Firefox 51.0.1

**Comment by Buddabread** [comment] 2017-03-03 00:33
I have the same Issue, please fix it in future.

**Comment by Gared** [comment] 2017-03-07 22:58
Same issue for me.
Threema Web version: 1.0.5
Browser: Firefox 51.0.1

**Comment by sebkraemer** [comment] 2017-04-07 13:46
Same problem here with Firefox 52 64bit under Linux, CPU around 50% constantly.
Scrolling-up-down doesn't appear to make a difference..

**Comment by rugk** [comment] 2017-04-07 15:23
This issue is not about CPU usage. Just FYI, in case this information was not posted deliberately.

**Comment by sebkraemer** [comment] 2017-04-09 11:45
Yes, thanks, wrong tab.. I corrected the comment.

**Comment by Buddabread** [comment] 2017-04-20 15:10
It seems like a graphical Issue within the web-Interface. Shouldn't be that hard to solve...
If you need more details, like a short Video clip, please let me now.

**Comment by rugk** [comment] 2017-04-21 07:00
I think it is a functional issue, because when I (regularly) have it, I can try to type and press enter at the end, but AFAIK this does not send any message. Or has anyone experienced a different behaviour?

**Comment by rugk** [comment] 2017-05-16 17:58
This bug is horribly annoying as you begin to type and suddenly (when typing two sentences or so) you notice it did not work and you have to write it all again. Then you nearly smash your keyboard until you  finally bethink yourself of using the correct workaround, so you click on another contact, (need to) wait until the chat there is loaded and finally click on the current contact again…
That's awful…

**Comment by dbrgn** [comment] 2017-05-16 21:30
I never experienced that issue, so it's hard to fix. Therefore it's probably FF related (I usually use Chromium).

Does it maybe only happen after a reconnect with the conversation open?

**Comment by rugk** [comment] 2017-05-17 08:20
No it happens purely random. Maybe only FF, yes.

**Comment by rugk** [comment] 2017-05-27 13:49
Actually maybe it happens a bit more often directly after reconnecting. So the first chat/input box you want to type in, does not work…

**Comment by rugk** [comment] 2017-06-14 10:29
Another workaround is to open the Emoji picker (click on it) and then you can already type the text again and your cursor is in the input field.

BTW it also sometimes happens when switching from a chat to another one.

**Comment by dbrgn** [comment] 2017-06-21 13:49
I started using Firefox more often in the last few days and the issue just happened to me too.

There are two nested `div`s.

```html
<div>
<div class="compose ng-scope" translate="" translate-attr-data-placeholder="messenger.COMPOSE_MESSAGE" autofocus="" data-placeholder="Type a message or drop a file" contenteditable=""></div>
</div>
```

Only the inner one is contenteditable. But it looks like somehow the cursor gets inserted into the outer div (since it's positioned at the very left corner, while the inner div has a padding of 8px).

Not sure how exactly it happens. It's hard to debug, since the field loses focus when opening the debug tools.

**Comment by lgrahl** [comment] 2017-08-08 12:17
@dbrgn This issue here happens to me frequently now on a Ubuntu system in the lab with Firefox 54. Anything I can do to help debugging this?

**Comment by rugk** [comment] 2017-08-08 13:30
The thing it this is difficult to debug, because once you open the debugging console (F12) the issue also disappears.

**Comment by lgrahl** [comment] 2017-08-09 15:49
Found the problem. It's the padding (8px). If you click at the padding, the
cursor jumps to the right or just below where the padding ends (hard to
describe) and you can't edit the inner div. I'm assuming this will be a
common issue (search for *padding* and *contenteditable* - there are some
results) and there will be a workaround. :)

**Comment by lgrahl** [comment] 2017-08-09 20:51
In Chrome, you can click on the padding and the cursor changes to *text editing* mode but rather than selecting the nearest character it jumps to the end of the text. If you click outside the padding area (e.g. further inside), the cursor jumps to the expected position.

In Firefox 54, the padding sort of creates a sub-element where, when selected, the cursor is inside of the padding element but nothing can be edited. It's really weird - that's definitely a bug.

One solution would be to move the padding into the parent. Then, the text cannot be selected when clicking inside the padding but at least the cursor placement is consistent (because it only works if you're actually clicking inside of it). On the other hand, it's really annoying that one cannot select text by clicking at the padding.

Another solution would be to increase the line height to simulate padding but that looks shitty for multi-line texts.

The last solution would be to ignore all of this and hope that browser vendors fix it. Find the associated bug reports or create ones.

**Comment by rugk** [comment] 2017-08-10 10:41
I cannot really reproduce it based on your description. In FF 54 I changed the padding to 80px to make it easier to click on it and if I click on the padding, it always – correctly – shows a cursor in the non-padding (i.e. the content) part and I can write…

**Comment by dbrgn** [comment] 2017-11-14 10:35
I experienced this again a few times and just cannot reliably reproduce it :( The thing is that we can't test a potential fix as long as the problem itself isn't reproducible.

**Comment by lgrahl** [comment] 2017-11-14 11:07
@dbrgn I can usually reproduce this on a specific PC. Contact me for testing.

**Comment by studersi** [comment] 2018-02-28 09:51
I also frequently come across this problem but I have never been able to reproduce it on purpose.

It does seem to mostly happen when I come back to the Threema Web tab after having worked in a different tab or in a different desktop application. But sometimes it also happens right after I sent a message by hitting the Enter key and want to type the next message.

It always disappears when I switch chat and come back or if I just click inside the chat window and then in the text field again.

When the problem happens, the cursor sometimes remains at its usual place, but often it is displaced as described @rugk. In one case it was displaced to the far right of the text field.

I'm running Threema Web 1.8.2 on Linux Mint 18 in Firefox 58.0.2 (64-bit).

**Comment by ovalseven8** [comment] 2018-03-02 11:14
Similar to this issue and reproducible, so it could be helpful:

1. Go to a chat
2. Click a little bit to the left of the cursor (see image):
![bildschirmfoto_2018-03-02_12-06-30](https://user-images.githubusercontent.com/8258609/36896430-f285ba80-1e12-11e8-9af8-473282806a99.png)
3. Now the cursor is on the right:
![bildschirmfoto_2018-03-02_12-08-40](https://user-images.githubusercontent.com/8258609/36896458-1358cf22-1e13-11e8-9126-26defa8473a4.png)
4. Now just press blank key
5. Cursor is somewhere left again (little bit more at the bottom):
![bildschirmfoto_2018-03-02_12-11-03](https://user-images.githubusercontent.com/8258609/36896475-25d3a370-1e13-11e8-800b-1fa1317dc4e9.png)
6. Try to click on input field
7. Does not work -> Cannot write anything!

(Using Firefox 58.0.2)

**Comment by lgrahl** [comment] 2019-03-11 12:44
I can't reproduce this any longer. If anyone can reproduce it with Firefox >= 65.x, please let us know. *Wontfix* since if FF >= 65.x is not affected, it will eventually land in ESR.

**Closed by lgrahl** 2019-03-11 12:44 UTC
Labels: bug
