### ISSUE TITLE
Inactive contacts are shown by default in each session

### ISSUE THREAD

**Issue by Buddabread** [threema-ch/threema-web#140] opened 2017-03-07 13:58 UTC
## Expected Behavior
Threema Web should always display the same contacts as on the mobile phone.
If the checkbox in the settings "show inactive ID's" is not checked, then Threema Web should also hide the inactive ID's.

## Current Behavior
The inactive ID's are shown by default, it doesn't matter if the checkbox "show inactive ID's" is set or not.
A workaround for this behaviour can be done by going in the settings, check and uncheck the checkbox and than the contacts are displayed normally.

## Possible Solution
Consider inactive ID's when Threema Web is starting.

## Your Environment

* Threema Web version: Version 1.0.5
* Threema for Android version: 3.11.344
* Threema for Android source: Threema Store
* Browser name and version: Mozilla Firefox 51.0.1 (32-Bit)
* Operating system and version: Windows 10

**Comment by dbrgn** [comment] 2017-03-07 14:04
Thanks for the report. It's a duplicate of #4 though.

**Closed by dbrgn** 2017-03-07 14:04 UTC
