### ISSUE TITLE
Messages marked as seen in inactive session.

### ISSUE THREAD

**Issue by ranguwud** [threema-ch/threema-web#108] opened 2017-02-28 08:45 UTC
## Expected Behavior
When the Window/Tab with Threema Web is not active/visible new incoming messages should not be marked as "seen" immediately.

## Current Behavior
If the conversation with contact X is selected in Threema Web and the Window/Tab is not active, all incoming messages from X will be marked as "seen" automatically. On the mobile device, any incoming message from X will create a sound/vibration and a notification is very briefly shown, but vanishes immediately after, thus leaving no trace of the unread message without opening the app. The status LED remains dark. This is particularly impractical e.g. when leaving the computer for a break and only locking its screen but not logging off Threema Web.

## Possible Solution
It should be possible to check, whether there is user interaction with Threema Web and mark incoming messages as "seen" only, if the user has focus on Threema Web. Possible approaches might be to check, whether the tab Threema Web resides in is active, or to watch for mouse moves/clicks or keystrokes sent to the tab. An option to fine-tune notifications on the mobile device, while working with Threema Web, as suggested in #21 might be helpful.

## Steps to Reproduce (for bugs)
1. In Threema Web, open conversation with contact X.
2. Leave Threema Web unattended, e.g. by switching tab, leaving the browser or locking the screen.
3. Have contact X send a message to you.
4. Notice that incoming messages are immediately marked as "seen" and that that the mobile device will vibrate/play a sound but that it won't show any notifications.

## Your Environment
* Threema Web version: 1.0.3
* Threema for Android version: 3.01.2000340
* Threema for Android source: Play Store
* Browser name and version: Firefox 51.0.1
* Operating system and version: Windows 7

**Comment by ranguwud** [comment] 2017-02-28 08:49
Issue #21 is related to this issue, but not a duplicate in my opinion. While I am missing notifications on the mobile device when on Threema Web, OP of #21 wants to turn off notifications on the mobile device. In general, of course, an option in the app to fine-tune the behavior would be most helpful.

**Comment by dbrgn** [comment] 2017-02-28 08:59
Related discussion: https://github.com/thenikso/angular-inview/issues/111

I'll give it a stab independently from the angular-inview implementation though.

**Comment by ovalseven8** [comment] 2017-02-28 09:50
Isn't this issue a duplicate of #17?

**Comment by dbrgn** [comment] 2017-02-28 12:21
> Isn't this issue a duplicate of #17?

No, it's a different issue (see #108).

**Comment by dbrgn** [comment] 2017-02-28 12:22
> Isn't this issue a duplicate of #17?

It's similar, but not the same technical cause.

**Comment by dbrgn** [comment] 2017-03-07 09:17
Actually I apparently mis-read the description of #17. This is a duplicate indeed.

**Closed by dbrgn** 2017-03-07 09:17 UTC
Labels: feature, ui
