### ISSUE TITLE
iOS quotes fail to resolve properly on Android WebUI

### ISSUE THREAD

**Issue by karalabe** [threema-ch/threema-web#1046] opened 2021-03-18 14:39 UTC
## Bug Description

Quoting someone (from iOS) displays the wrong author on the web UI. The issue seems to be similar to https://github.com/threema-ch/threema-web/issues/1041, but for me on Android, the ID doesn't even resolve on the WebUI and remains the unique Threema ID.

![Screenshot from 2021-03-18 16-16-43](https://user-images.githubusercontent.com/129561/111642491-cf0f4d80-8806-11eb-9b7b-0a5d635c96f1.png)

However, it does correctly resolve in the Android app.

![Screenshot_20210318-162820_Threema](https://user-images.githubusercontent.com/129561/111643093-58268480-8807-11eb-9b66-c372b140ba03.jpg)

Thus it seems to be not only an iOS app bug, rather something deeper.

## Steps to Reproduce (for bugs)

1. Quote an Android user on iOS app v4.6.5
2. Check quoted message on Android
3. Check quoted message on WebUI through Android
4. Latter doesn't resolve

## Your Environment

* Threema Web version: 2.3.11 on both iOS and Android
* Threema App version: 4.6.5 on iOS, 4.52 on Android

**Comment by threema-danilo** [comment] 2021-03-18 18:21
@threema-jarem probably still a duplicate of #1041, right?

**Comment by threema-danilo** [comment] 2022-04-26 09:13
As far as I know, this was fixed long ago. Please comment if the issue still persists.

**Closed by threema-danilo** 2022-04-26 09:13 UTC
Labels: bug, awaiting triage
