### ISSUE TITLE
improve emoji selector hide button

### ISSUE THREAD

**Issue by SimJoSt** [threema-ch/threema-web#223] opened 2017-05-16 10:17 UTC
## Steps to reproduce
1. Open chat
2. click on emoji face to expand emoji selector

## Expected Behavior
I expect to find a button which is obvious to collapse the emoji selector again.

## Current Behavior
There is none. Only the emoji face I clicked before, which can be toggled again.

## Possible Solution
WhatsApp Web has solved this appropriately:
The emoji toggler itself toggles from emoji face to downward facing arrow.

**Comment by dbrgn** [comment] 2017-05-16 11:13
Duplicate of #224.

**Comment by SimJoSt** [comment] 2017-05-19 16:49
I actually opened these issues separately to make it possible to discuss them on their own :-)

**Comment by dbrgn** [comment] 2017-05-19 16:52
Ah, I see. I thought it was the same issue.

I'm sceptical whether a change of the icon is needed, but I'll re-open this for now.

**Comment by sillych** [comment] 2017-08-17 07:24
we don't think this is necessary.

**Closed by sillych** 2017-08-17 07:24 UTC
Labels: ui
