### ISSUE TITLE
Retry button for 12% issue

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#206] opened 2017-04-30 12:22 UTC
## Expected Behavior

When the connection cannot be restored (stuck at 12%) there should be a "Try again" button.

## Current Behavior

You have to reload the site and only if the server connection is lost there is a "reload" button.

## Possible Solution

Add that button.

## Steps to Reproduce (for bugs)

Cause the issue https://github.com/threema-ch/threema-web/issues/106.

## Your Environment

* Threema Web version: 1.1.0

**Comment by lgrahl** [comment] 2017-07-13 16:17
Question is: What do you want to retry? When the browser waits for the app on the SaltyRTC path and the app simply does not connect to it (because it hasn't received the push message, is offline, can't reach the server, ...), there's not much you can do about it. At best, you can re-send the push message.

**Comment by rugk** [comment] 2017-07-13 17:37
(see STR)

Yeah, theoretically, yes. But when the issue https://github.com/threema-ch/threema-web/issues/106 happens, I regularly have to retry the whole process, just reloading the whole thing and retry it…
And sometimes it does work.

**Comment by lgrahl** [comment] 2017-07-13 18:28
It sometimes works because your Android phone miraculously (the Google push service seems somewhat erratic) receives the push message and/or finally connects to the SaltyRTC path. The simplified flow for the app in this case is:

1. Receive a push message.
2. Connect to signalling path.
3. SaltyRTC handshake.
4. Create a peer-to-peer connection.

We never get to 3), so the app can either be at 1) or 2). Thus, all that can be effectively retried is sending another push message. But you can also tap *start* on the corresponding session in the app and it will continue from 12% unless the app cannot establish a WebSocket connection.

My proposal would be to send push messages in a moderate interval in the background (actually, that's a potential fix for #106). This basically is a retry button without the need for a user to press it. :wink:

**Comment by rugk** [comment] 2017-07-13 18:47
> But you can also tap start on the corresponding session in the app and it will continue from 12% unless the app cannot establish a WebSocket connection.

I know, this always works.

So maybe just make a button **"Resent push message"** instead?
Maybe that's better than actually automatically retrying to sent the push. I mean what is "a moderate interval". AFAIK the push message is valid for 1 min, but we don't want to wait so long for sending another push. But we also don't want to send the push message too fast…
Let the user decide when to sent another push message. And maybe name the button "Retry" anyway, as most users do not care about the technical background, i.e. push messages…

**Comment by dbrgn** [comment] 2017-07-13 18:51
If the issue is that the app is killed immediately by Android after receiving the push notifications because free memory is low or to save energy, then sending another push won't help. (Bringing the app to foreground will.)

We have other ideas in mind to improve the situation inside the app, but that might take a while to implement and test.

**Comment by rugk** [comment] 2017-07-13 19:04
If that's the issue… but maybe it does help in other cases…

**Comment by lgrahl** [comment] 2017-08-08 12:14
@dbrgn Do you guys still need this as a reminder or can this be closed? Sounds like you decided against a retry button.

**Comment by dbrgn** [comment] 2017-08-10 14:18
We can close this. If a retry makes sense, it should happen automatially. I just need to find time to implement a fix (hopefully) for the 12% issue, but it's planned :)

**Closed by dbrgn** 2017-08-10 14:18 UTC
