### ISSUE TITLE
Compose area issues

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#808] opened 2019-05-23 19:03 UTC
## Steps to Reproduce (for bugs)
1. Write something (e.g. 'ABC')
2. Eight linebreaks (<kbd>Shift</kbd>+<kbd>Enter</kbd>)
3. Write some else (e.g. 'defgh')
4. Go to the top of your input again.
5. Try to set the cursor at each line in your input widget
6. You'll see that this does not work for the lines at the lower end
7. When you try to set the cursor in one of the lines at the lower end, the second input ('defgh') will be marked. However, you cannot delete it when you press <kbd>Backspace</kbd>

Note that this behavior is in both the beta and current stable version.

![Peek 2019-05-23 20-52](https://user-images.githubusercontent.com/8258609/58279069-b3b79080-7d9d-11e9-9b78-389adf411439.gif)

## Expected Behavior
- Marked content is deletable when pressing <kbd>Backspace</kbd>
- You can set the cursor at each line

## Your Environment
* Threema Web version: Version 2.2.0-beta.1 Glärnisch
* Browser name and version: Firefox 67

**Comment by dbrgn** [comment] 2019-05-23 21:48
Thanks for the detailed report. This seems to be a duplicate of #111. It only seems to happen in Firefox.

Unfortunately so far I haven't yet found out what the reason for the behavior is, but it's on my TODO-list to investigate some more.

**Closed by dbrgn** 2019-05-23 21:48 UTC
