### ISSUE TITLE
Very high cpu load while using webclient

### ISSUE THREAD

**Issue by rohlandm** [threema-ch/threema-web#39] opened 2017-02-15 23:34 UTC
While using the web client, I have a very high CPU load, using both Google Chrome and Vivaldi (Chromium based). I have attached a screenshot of the chrome task manager:

![threema_cpu](https://cloud.githubusercontent.com/assets/2794686/23000133/56d702c8-f3df-11e6-894f-3b741db1718b.png)

This issue hinders me from using the web client in a "normal-use scenario", keeping it open in a pinned tab.

Edit:
I use Ubuntu 16.10 on a Dell XPS 13 (9360)

**Comment by offlinehoster** [comment] 2017-02-16 05:53
Same problem with Ubuntu. High CPU usage by 105-110 %.

After closing that threema web app tab it is going down to the regulat 1-8 %....

Ubuntu 16.04 LTS (64bit)
Firefox 51.0.1 (64bit)

**Comment by 2b-as** [comment] 2017-02-16 10:57
Same issue here on OSX 10.11.6 with Firefox 51.0.1, but _only_ in the messaging/chat view.

As soon as I return to the overview of contacs with their last messages, CPU usage drops to almost normal levels.

**Comment by meyerjo** [comment] 2017-02-16 11:35
Same issue on Windows 10 with 56.0.2924.87 (64-bit) (only in the messaging view)

**Comment by rugk** [comment] 2017-02-16 15:39
dupe of https://github.com/threema-ch/threema-web/issues/20 (or at least closely related)

**Comment by fichtennadel** [comment] 2017-03-01 06:51
Some details for this issue on FF 51.0.1 on Win7: 

The CPU load goes only up to 100%, when chat/messaging view is open. 
As soon as I close the indivdial chat by clicking ◀️ and returning to the contacts overview, CPU is down to idle again. 

Javascript debugger "pause" button stops repeatedly in `angular-material.min.js`:
`var n = e.Math.max(0, e.Math.min(i.now() - h, E));`

Call stack:

    f@https://web.threema.ch/node_modules/angular-material/angular-material.min.js?v=1.0.3:13822:0
    $@https://web.threema.ch/node_modules/angular-material/angular-material.min.js?v=1.0.3:13829:0
    callback@https://web.threema.ch/node_modules/angular/angular.js?v=1.0.3:12908:10
    completeOutstandingRequest@https://web.threema.ch/node_modules/angular/angular.js?v=1.0.3:6045:6
    Browser/self.defer/timeoutId<@https://web.threema.ch/node_modules/angular/angular.js?v=1.0.3:6324:6


Hope this helps.

**Comment by dbrgn** [comment] 2017-03-01 07:29
Thanks @fichtennadel! That made me take a closer look at the profiler again, and I think I found the cause of the high CPU use now :)

**Comment by dbrgn** [comment] 2017-03-01 12:39
In case someone wants to test, the `less-progressbars` branch should improve the situation: #117

**Comment by fichtennadel** [comment] 2017-03-01 13:25
> In case someone wants to test, the less-progressbars branch should improve the situation

Can't test the branch, but after reading the description of the fix, I had the idea to remove all the progress bars by scrolling up the history to the top: After the top circle vanished, CPU load goes down.

**Comment by dbrgn** [comment] 2017-03-01 17:21
The fix from #117 is now live on https://web.threema.ch/, as of v1.0.4.

Would be good to get some feedback from @fichtennadel @meyerjo @2b-as @offlinehoster @rohlandm on whether the CPU load is fixed or at least greatly reduced.

**Comment by lgrahl** [comment] 2017-03-01 18:04
Firefox: CPU load still starts going up once a conversation is being opened ~40%. When the conversation is being closed, it goes down immediately to ~idle%. I can send you a profile if you want me to.

**Comment by 2b-as** [comment] 2017-03-01 18:26
Firefox / OSX: I can confirm what @lgrahl said. CPU usage now 40% instead of 100% in conversation view.
Interesting detail: If I scroll up to the first message in a conversation, CPU usage goes down to normal level and stays there as long as this particular conversation stays opened, even if I scroll down again. Once I close and re-open that conversation, CPU load goes to 40% again.

**Comment by sillych** [comment] 2017-03-01 18:36
@2b-as do you habe a lot of thumbnail images in this conversation?

**Comment by 2b-as** [comment] 2017-03-01 18:46
@sillych Number of images doesn't seem to have any influence on CPU load

**Comment by sillych** [comment] 2017-03-01 19:09
@2b-as thanks!
i can reproduce the high CPU load:
- open a conversation with a lot of text messages
- moving the mouse rapidly over different the chat bubbles

**Comment by fichtennadel** [comment] 2017-03-01 19:36
> Firefox: CPU load still starts going up once a conversation is being opened ~40%.

For me it's a bit better than before: load at about ~15% instead of 50%, but the difference to lgrahl is probably just the display value, it's the same order of magnitude.

> If I scroll up to the first message in a conversation, CPU usage goes down to normal level and stays there as long as this particular conversation stays opened, even if I scroll down again. Once I close and re-open that conversation, CPU load goes to 40% again.

Same for me (modulo % load as above).

My guess is, it's related to the number of unloaded items and/or images: if I scroll upwards multiple times to the top, as long as the circle on the very top still circles until the one on the top vanishes, load is down to idle.

**Comment by rohlandm** [comment] 2017-03-01 23:48
I can confirm that with 1.0.4 the load while scrolling through a conversation is between 5 and 15% and close to zero if left alone.

**Comment by offlinehoster** [comment] 2017-03-02 06:40
Currently it looks good on Ubuntu Linux with Firefox.

**Comment by ovalseven8** [comment] 2017-03-02 16:20
When I click on a contact and the conversation is loaded, the CPU load is sometimes up to ~90 %. Is this normal?

**Comment by dbrgn** [comment] 2017-03-02 16:27
@ovalseven8 During the loading, or even after everything has been loaded for a while?

**Comment by ovalseven8** [comment] 2017-03-02 16:42
During the loading.

**Comment by dbrgn** [comment] 2017-03-02 16:56
Yes, that is currently expected. AngularJS does a lot of things in the background (many watches being fired at the same time, some animations being calculated). As always, frameworks give us big advantages, but also have their downsides. Performance is one of the downsides for Angular.

We'll probably tackle #40 some time in the future, that should help a lot.

**Comment by ovalseven8** [comment] 2017-03-02 17:00
Unfortunately, I can't help here. :(

And I am sure you know all the interesting posts about AnulgarJS performance already ;)
https://www.alexkras.com/11-tips-to-improve-angularjs-performance/

**Comment by dbrgn** [comment] 2017-03-02 17:04
Yep, numbers 1, 2 and 5 are what we are trying to improve in #40 :)

**Comment by fichtennadel** [comment] 2017-03-03 14:50
To me it seems manually painting the "loading" circle in JS causes the load. What about using a gif image instead?

**Comment by dbrgn** [comment] 2017-03-03 20:23
> To me it seems manually painting the "loading" circle in JS causes the load.

Which one, the one that appears when loading older messages? That's not animated with JS anymore, it's now pure CSS. There are still some animated through JS though, namely the ones that appear on a thumbnail when downloading a file. That's still on my TODO list.

**Comment by fichtennadel** [comment] 2017-03-14 13:54
> Which one, the one that appears when loading older messages?

I don't know, I just see that FF load is up to 20% (Chrome a little bit better: 8%) until I do once a full scroll up to the very first message. 

So I guess this must be related to the "unvisited" messages, because as soon as I reach the start of the chat, load is <1% in both FF and Chrome. 
Note that this is not related to the media in the chat being fully loaded: Even if there are still images and videos not fully loaded (unsharp/turning circle), load is <1% **if** one time scrolled up to the top.

Can you reproduce this?

**Comment by fichtennadel** [comment] 2017-03-16 18:36
> FF load is up to 20% (Chrome a little bit better: 8%) until I do once a full scroll up to the very first message.

Slight improvement with release 1.1.0, but load still constant at ~8% in FF until I do the "scroll up/down workaround"

Can anyone else confirm this "scroll up/down workaround"? Maybe this gives a hint to the cause of the load issue.

**Comment by 2b-as** [comment] 2017-03-17 08:26
Yes, the "scroll up/down workaround" also works for me.

**Comment by dbrgn** [comment] 2017-03-24 14:49
Fun story: https://github.com/Microsoft/vscode/issues/22900 (was #1 on Hacker News yesterday). Seems that CSS animations really are implemented quite inefficient.

We should probably replace the loading spinner with an old fashioned GIF.

**Comment by fichtennadel** [comment] 2017-03-25 07:55
+1 for the old fashioned GIF, at least you could give it a try if it's better than CSS in our case

**Comment by sebkraemer** [comment] 2017-04-09 11:47
Same problem here with Firefox 52 64bit under Linux, CPU around 50% constantly.
Scrolling-up-down doesn't appear to make a difference..

**Comment by offlinehoster** [comment] 2017-07-07 05:01
How long can this take to fix?

Even those others are able to provide an own app for example with much lower cpu usage than Threema.

I mean...using Threema would be much more efficient if the cpu would not consumpt over 50% to sometimes 100% of cpu power and so off batterytime…

**Comment by lgrahl** [comment] 2017-07-07 09:33
@offlinehoster While I understand your concern, your posting is not constructive. However, I agree that this bug should take high priority.

**Comment by offlinehoster** [comment] 2017-07-07 09:40
I totally agree with you @lgrahl , but what else could i do as a simple Threema user to get back to the table and talk about my bad user experiences? 

sry for the (cpu fan) noise.

**Comment by lgrahl** [comment] 2017-07-07 09:44
I'd say *penetrant pinging* in the issue is fine. :wink: Which is what we're doing right now.

**Comment by dbrgn** [comment] 2017-07-07 10:16
As a workaround you can use Chrome for now, where the CPU consumption isn't that bad.

We're aware of the issue, but with limited manpower setting development priorities is hard :) At least the GIF / spinner issue should be fixed in one of the next 1 or 2 releases, that might already help.

Help is always welcome of course.

**Comment by dbrgn** [comment] 2017-07-10 12:59
By the way, in current Firefox Nightly Threema Web barely uses 1% of CPU when idle. The animation is still executed though, but runs at 60 fps. So it seems that they fixed the performance bug of simple animations using 10% CPU.

**Comment by dbrgn** [comment] 2017-07-10 13:31
#264 was just merged. Tests of current master would be welcome :) Should land in the next release.

**Comment by dbrgn** [comment] 2017-07-20 09:40
The fix from #264 is now deployed in Threema Web 1.4.0.

Is CPU load still an issue?

**Comment by ovalseven8** [comment] 2017-07-20 10:55
It feels like the performance improved IN THE CONVERSATION AREA and that the animation disappears faster and the messaging are there instead, what is good. :+1: 
However, when you want to **open another conversation**, it still is VERY slow and takes quite a while so that the messages are there. But when the conversation is loaded, it is faster now.

So, I guess the next step should be improving performance when opening other conversations.

Here some CPU information (using Firefox):

**When I move the mouse rapidly over different chat bubbles:**
![2017-07-20-123737_1366x768_scrot](https://user-images.githubusercontent.com/8258609/28413661-b605c1c0-6d48-11e7-951c-5d67ea928a15.png)
![2017-07-20-123740_1366x768_scrot](https://user-images.githubusercontent.com/8258609/28413663-b97388c4-6d48-11e7-8dc5-9cab70effd62.png)
![2017-07-20-123750_1366x768_scrot](https://user-images.githubusercontent.com/8258609/28413669-bcb0f2ba-6d48-11e7-86a6-efa1d910708b.png)
![2017-07-20-123752_1366x768_scrot](https://user-images.githubusercontent.com/8258609/28413674-bf9f5d40-6d48-11e7-848d-b32c8a600e63.png)

**When I do nothing (with Threema Web open):**
![2017-07-20-124218_1366x768_scrot](https://user-images.githubusercontent.com/8258609/28413777-1a916216-6d49-11e7-8db2-ea98579b4d8f.png)
![2017-07-20-124229_1366x768_scrot](https://user-images.githubusercontent.com/8258609/28413781-1d7eae7a-6d49-11e7-9dfa-b1eadb8e1e15.png)
![2017-07-20-124231_1366x768_scrot](https://user-images.githubusercontent.com/8258609/28413785-2024e5e0-6d49-11e7-84a8-7094a4e2bfd5.png)
![2017-07-20-124237_1366x768_scrot](https://user-images.githubusercontent.com/8258609/28413789-22acfbea-6d49-11e7-9452-a56fae3cb173.png)

**When I open (another) conversation:**
![2017-07-20-124630_1366x768_scrot](https://user-images.githubusercontent.com/8258609/28413961-cec577a4-6d49-11e7-9d9f-3f6bb2541bbc.png)
![2017-07-20-124632_1366x768_scrot](https://user-images.githubusercontent.com/8258609/28413963-d2c3566e-6d49-11e7-8e6b-f170497c2535.png)
![2017-07-20-124638_1366x768_scrot](https://user-images.githubusercontent.com/8258609/28413967-d5a23b66-6d49-11e7-8a6b-dd30fa264f7f.png)
![2017-07-20-124647_1366x768_scrot](https://user-images.githubusercontent.com/8258609/28413969-d832643c-6d49-11e7-9fc9-905deedb3bae.png)
![2017-07-20-124648_1366x768_scrot](https://user-images.githubusercontent.com/8258609/28413975-db26af9a-6d49-11e7-9d6f-5ddca6c4a2a9.png)

**Comment by 2b-as** [comment] 2017-07-20 11:17
Firefox CPU load while in conversation view: ~ 5%
Firefox CPU load if not in conversation (where the contacts are listed):
~ 0.5%

So, much better than before.

**Comment by rugk** [comment] 2017-07-24 13:35
BTW: If you need to want to use a better thing instead of the gif spinner, maybe use the new format APNG… It is quite widely [supported](https://caniuse.com/#search=APNG) – at least for the browsers you can support, because of WebRTC.

**Comment by dbrgn** [comment] 2017-07-25 07:01
> However, when you want to open another conversation, it still is VERY slow and takes quite a while so that the messages are there.

Yes, but in that case a lot of things are happening at the same time, so (at least currently) it's expected.

Speeding up the loading of conversations is planned. Among other things, #273, #272, #40 and others should also improve the situation.

Will close this for now, since the main problem (high load even when idle) should now be solved.

**Closed by dbrgn** 2017-07-25 07:01 UTC
Labels: bug
