### ISSUE TITLE
Favicon not shown in Safari if tab is pinned

### ISSUE THREAD

**Issue by joelfischerr** [threema-ch/threema-web#503] opened 2018-05-31 07:52 UTC
## Expected Behavior
A favicon should be shown when the tab with web-beta.threema.ch open is pinned.
![screenshot](https://user-images.githubusercontent.com/2352766/40769009-2cd37124-64b7-11e8-89fa-ef97c1831337.png)

## Current Behavior
No favicon is shown.

## Possible Solution
Show favicon. 
Possibly relevant StackOverflow answer: https://stackoverflow.com/a/48969053/2310837
Safari docs: https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html

## Steps to Reproduce (for bugs)
1. Open web-beta.threema.ch
2. Pin tab
3. No favicon is shown

## Your Environment

* Threema Web version: 2.0.0-beta.1
* Threema for ~Android~ iOS version: 4.0 (2309)
* Threema for ~Android~ iOS source: Testflight
* Browser name and version: Safari 11.1 (13605.1.33.1.4)
* Operating system and version: macOS 10.13

Sorry for being nitpicky. 
Should I send other improvements only concerning Threema Web and not the iOS app directly to the email specified in Testflight or open an issue here?

**Comment by rugk** [comment] 2018-05-31 08:28
I'd suggest to use https://realfavicongenerator.net/. They did all compatibility tests, etc.

**Comment by dbrgn** [comment] 2018-05-31 20:04
Thanks for the report. @joelfischerr if the problem is about the Threema Web UI, then you can open issues here. Otherwise, it's best to report iOS issues via testflight.

**Comment by dbrgn** [comment] 2018-06-04 12:09
Fixed in #508.

**Closed by dbrgn** 2018-06-04 12:09 UTC
Labels: easy, ui

**Comment by joelfischerr** [comment] 2018-06-04 19:57
I feel like I have to apologise for the OS and browser I'm using. But if the favicon does not show up for anyone else, deleting ~/Library/Safari/Template Icons and then restarting Safari should help (described here in more detail https://yoast.com/dev-blog/safari-pinned-tab-icon-mask-icon/).
