### ISSUE TITLE
wrong emoticon for "sun" in threema web

### ISSUE THREAD

**Issue by fichtennadel** [threema-ch/threema-web#194] opened 2017-04-10 07:43 UTC
## Expected Behavior
emoticons consistent in app and web

## Current Behavior
emoticon for "sun" from app ...
![image](https://cloud.githubusercontent.com/assets/2324670/24848290/4cc93a60-1dc6-11e7-8106-5f110454e3c0.png)

... is shown as "policeman" in threema web
![image](https://cloud.githubusercontent.com/assets/2324670/24848237/21a3b482-1dc6-11e7-9072-2fd00ea6efa8.png)

Leaves room for funny misunderstandings ;-)

Important to reproduce is that the message has been sent from an iOS device (latest version of Threema installed), the sun is shown on both apps (Android and iOS), but threema web displays the policeman. 
Interesting: it's ok in the message preview in the notification, but not in the chat.

I couldn't reproduce this when sending from Android, only from iOS.

## Your Environment
* Threema Web version: 1.1.0
* Threema for Android version: 3.13.2000346
* Threema for Android source: Play Store
* Browser name and version: FF 52.0.2 
* Operating system and version: Win7

**Comment by dbrgn** [comment] 2017-04-10 07:45
Duplicate of #54.Unfortunately emojione have delayed their release yet again, it's now scheduled for mid-April. That release should fix this issue though.

**Closed by dbrgn** 2017-04-10 07:45 UTC
