### ISSUE TITLE
Threema Web loses connection

### ISSUE THREAD

**Issue by madrino** [threema-ch/threema-web#151] opened 2017-03-09 11:22 UTC
![threema_web_connetion](https://cloud.githubusercontent.com/assets/26299691/23748539/507b210c-04c4-11e7-9ebc-13b2b69919fd.jpg)

After a few minutes Threema Web loses the connection.

When i press F5 Threema Web works fine until Threema Web loses the connection again.

**Comment by dbrgn** [comment] 2017-03-09 13:09
Thanks for the report. Technically, this is a duplicate of #106.

The next app and web releases should both contain improvements for this.

**Closed by dbrgn** 2017-03-09 13:09 UTC
