### ISSUE TITLE
Mail (✉️) and light brown Police (👮🏼) Emoji are switched

### ISSUE THREAD

**Issue by dns2utf8** [threema-ch/threema-web#187] opened 2017-03-23 15:19 UTC
## Expected Behavior

Emojis should look the same as in the app.

## Current Behavior

The conversation and the preview are wrong.
![screenshot_20170323_161552](https://cloud.githubusercontent.com/assets/739070/24254791/0f19e254-0fe4-11e7-8767-2f7296122408.png)

## Possible Solution

Render the correct Emoji in the conversation and the preview.

## Steps to Reproduce (for bugs)

1. Send the following text from any Threema Source: 👮🏼!= ✉️
2. Profit

## Your Environment

* Threema Web version: 1.1.0
* Threema for Android version: Neuste Playstore
* Threema for Android source: Play Store
* Browser name and version: Firefox 52.0.1 & Chromium 57
* Operating system and version: Arch Linux

**Comment by rugk** [comment] 2017-03-23 15:36
Can reproduce it. That's funny… :smiley:

**Comment by dbrgn** [comment] 2017-03-23 16:03
That's a duplicate of #54. We're waiting for a new Emojione release (which was originally kind-of announced for December last year...).

**Closed by dbrgn** 2017-03-23 16:03 UTC

**Comment by rugk** [comment] 2017-03-23 16:08
Okay, should not take much time:
> Official release and developer tools (with new 3.0 license) by March.
