### ISSUE TITLE
Bug after cancelling upload

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#426] opened 2018-02-12 14:44 UTC
## Expected Behavior
Just synchronize the cancellation of the upload

## Current Behavior
After cancelling the media upload, I **cannot open the chat in Threema web anymore.** Moreover, there is **this bug:**
![2018-02-12-153907_1920x1080_scrot](https://user-images.githubusercontent.com/8258609/36102047-58f7a47e-100b-11e8-8b24-b5dd1a533d76.png)

## Steps to Reproduce (for bugs)
1. Send a video via Threema Web
2. When transferred to the Threema app, cancel the upload to the Threema server in the app
3. This bug occurs

## Your Environment
* Threema Web version: 1.7.0
* Threema for Android version: 3.31
* Threema for Android source: Play Store
* Browser name and version: Firefox 58.0.1

**Comment by ovalseven8** [comment] 2018-03-02 11:52
Probably related to #393

**Comment by dbrgn** [comment] 2018-04-03 13:27
Duplicate of #393, should be fixed in #475.

**Closed by dbrgn** 2018-04-03 13:27 UTC
Labels: bug
