### ISSUE TITLE
Support the same smiley pack as in the app

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#263] opened 2017-06-30 21:51 UTC
Why does Threema Web use another smiley pack than the app?

For better consistency, I'd prefer to have the same smileys in both the app and Threema web.
Is there a specific reason why that's not the case?

In WhatsApp Web there are the same smileys than in the app.

**Comment by lgrahl** [comment] 2017-06-30 22:00
Probably because I used EmojiOne in the prototype as it *just works* and it's open source. (And to be honest, I think EmojiOne Emojis look a lot better than the Apple Emojis.)

**Comment by dbrgn** [comment] 2017-07-01 13:21
Duplicate of #146.

**Closed by dbrgn** 2017-07-01 13:21 UTC

**Comment by ovalseven8** [comment] 2017-07-01 13:42
Oh, didn't see that issue. :smile: 

Why is it locked by the way?

**Comment by ovalseven8** [comment] 2017-07-01 13:48
Oh, didn't see this issue. :smile: 

But I'd reopen #146 because it's not solved.

**Comment by dbrgn** [comment] 2017-07-01 20:10
Among other things it's a matter of taste, so discussion about it only generates unnecessary noise. We do not consider it a problem right now.
