### ISSUE TITLE
On Threema Web connection loss (rather than explicitly being thrown out or something), on reconnection don't make me reenter password

### ISSUE THREAD

**Issue by JonasT** [threema-ch/threema-web#483] opened 2018-03-30 16:27 UTC
## Expected Behavior
On temporary Threema Web connection loss to device or server (rather than explicitly being thrown out or something), the browser won't make me re-enter the session password.

## Current Behavior
On temporary Threema Web connection loss to device or server (rather than explicitly being thrown out or something), I always need to re-enter the password. 

## Possible Solution
Why can't the browser keep a temporary session cookie alive? (it could be HTTPS only and super short-lived and need to be "refreshed" actively while the tab is fully connected, and only allow reconnecting without password in a very short amount of time.) If the lack of this is meant to be a security-enhancing feature, it shouldn't be based on temporary connection loss anyway but rather too long idle activity or trying to restart the session after too long after a disconnect, rather than how often I temporarily lose the connection for a few seconds.

## Steps to Reproduce (for bugs)

1. Get thrown out of threema web session because connection to server and/or phone device was lost
2. Get prompted for session password to resume (even if you just started the session 10 minutes ago, and it worked for most of the time)

## Your Environment

* Threema Web version: 1.8.2
* Threema for Android version: 3.41.413
* Threema for Android source: threema website/store
* Browser name and version: firefox 61.0a1 (2018-03-28) (64-bit)
* Operating system and version: fedora 27 (gnu/linux)

**Comment by dbrgn** [comment] 2018-03-30 19:08
This is without GCM, right?

What happens is that when Threema Web loses connection, it tries to wake up the device. If you don't use GCM, then nothing happens because the device does not know that it needs to reconnect. After a certain timeout, the connection attempt in the browser times out and you need to reload the page (at which point the in-memory keys will be discarded). There is no session cookie or anything like that involved.

Essentially this is a duplicate of #482. Please comment if you disagree.

**Closed by dbrgn** 2018-03-30 19:08 UTC

**Comment by rugk** [comment] 2018-03-30 19:43
I think this one is just:

* Please save the password/key in the local storage (of course not session cookie or so, you don't use that), so I don't have to reenter it when reconnecting when the session breaks.

**Comment by JonasT** [comment] 2018-03-30 20:27
Yup. It is different, this one is talking about "re-enter session password" screen BEFORE the "please go on your phone and re-start the session" screen.

As for storing the password in local storage, that sounds like a bad idea - it'd be better if the server supported timed expiring tokens and only gave that one to the browser, since storing the password sounds significantly less secure (that's also why the browser's built-in save password function isn't really a replacement for this functionality).

**Comment by dbrgn** [comment] 2018-03-30 20:40
> it'd be better if the server supported timed expiring tokens

There is *no* server involved in this. The encryption between your phone and your browser is end-to-end encrypted.

If you use GCM then - unless something goes wrong - your connection is automatically re-established and you never see the password prompt unless you manually reload the browser window.

**Comment by JonasT** [comment] 2018-03-30 20:42
Ah okay. Yea I get the password prompt *every time*, I don't know how it'd work with GCM. I suppose both tickets can be summed up as "make it work without GCM as it does with GCM please".

**Comment by dbrgn** [comment] 2018-03-30 20:45
Even if we manage to get a workaround working, without a push service, it will *never* work as well as it does with GCM. In the best case, the connection will re-establish within less than a minute.

Have you thought about https://microg.org/ / https://lineage.microg.org/?

**Comment by JonasT** [comment] 2018-03-30 20:49
> In the best case, the connection will re-establish within less than a minute.

That would still be a huge improvement in my opinion. The most annoying part is that I need to do so much to reestablish it, not that it drops out sometimes.

**Comment by lgrahl** [comment] 2018-03-30 22:09
@dbrgn Wouldn't it be sufficient to connect to the SaltyRTC server on app side after connection loss in case of no GCM support? The app could wait there for a minute and if nothing happens just drop the connection again. I mean, IIRC that is what the browser side is doing.

Having said that, the reason for connection loss is likely the app being suspended in the first place...

**Comment by JonasT** [comment] 2018-03-31 02:12
> Having said that, the reason for connection loss is likely the app being suspended in the first place...

Not sure about that, I'm often getting this error: " Error: Connection to server has been closed.
Please reload the page to try again. " -  which at least makes it sounds like the threema web server thing loses connection to my browser?

**Comment by lgrahl** [comment] 2018-03-31 07:11
Yes but that's an *aftermath* reaction. I see that happening quite often too and believe it's a race condition of the WebSocket client. Is there an an open issue for that @dbrgn (WS disconnects, new WS connects, one of the initiators kicks the other with `3004`)?

**Comment by JonasT** [comment] 2018-04-03 14:34
> Yes but that's an aftermath reaction.

Well I see it at least once a day, often more, so if that shouldn't be happening maybe someone should look into it...?
