### ISSUE TITLE
Line that marks if chat list or contact list is active gets too long

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#845] opened 2019-07-09 17:20 UTC
## Bug Description
Every now and then I can observe the following phenomenon: The line in color `rgb(0,150,136)` is too long.
![Bildschirmfoto vom 2019-07-09 19-10-58](https://user-images.githubusercontent.com/8258609/60909161-d8989200-a27d-11e9-997c-e811a3dd29ba.png)

## Steps to Reproduce (for bugs)
No idea.

## Your Environment

* Threema Web version: Version 2.1.7 Glärnisch 
* Threema App version: 3.7 (Android)
* Browser name and version: Firefox 67.0.4
* Smartphone operating system and version: Android 6

**Comment by dbrgn** [comment] 2019-07-29 07:40
I've had that before too, and suspect it's a bug in the angularjs-material library that we're using. It's hard to reproduce unfortunately.

**Comment by lgrahl** [comment] 2019-07-29 09:19
I'd say this is `wontfix` since it really doesn't matter much. Close if you agree, @dbrgn.

**Comment by dbrgn** [comment] 2019-08-08 09:15
If someone manages to fix this, PRs are welcome! I tried a while ago and could not find the root cause.

Closing since it's not a functional problem and there are more important things that should be fixed.

**Closed by dbrgn** 2019-08-08 09:15 UTC
Labels: bug, ui, wontfix
