### ISSUE TITLE
Can't connect to Threema Web (since version 1.7?)

### ISSUE THREAD

**Issue by 90er** [threema-ch/threema-web#389] opened 2017-11-27 18:16 UTC
## Current Behavior
I'm not able to connect using Threema Web with Android. Threema Web version 1.6.2 worked like a charm, it fixed my long time issues with reconnecting.

## Steps to Reproduce (for bugs)
1. Start Threema Web in Firefox: https://web.threema.ch/#/welcome
2. Start Threema for Android
3. Scan QR-Code
4. Android Smartphone recognize the QR-Code and vibrate
5. Nothing happens - Firefox still at the QR-Code, Android App tries to load the Threema Web Session

![screenshot_20171127-191048](https://user-images.githubusercontent.com/17730136/33282002-7d9d3d7a-d3a7-11e7-85da-57811aadae9b.png)

## Environment
* Threema Web version: 1.7
* Threema for Android version: 3.3.2000387
* Threema for Android source: Play Store
* Browser name and version: Firefox 57
* Operating system and version: Windows 10 x64

**Comment by sillych** [comment] 2017-11-29 05:33
Please enable the log file (Threema > Settings > Troubleshooting > "Log to File"). After the problem has occurred again, please check the log file (/sdcard/Threema/message_log.txt) for some error messages or exceptions.

Also enable the developer tools in your firefox (CTRL+SHIFT+I) and check the console for some error messages.

**Comment by dbrgn** [comment] 2018-02-02 18:29
Since this doesn't seem related to the web frontend, I'll close this issue.

**Closed by dbrgn** 2018-02-02 18:29 UTC

**Comment by emmenlau** [comment] 2018-05-16 10:13
@dbrgn I have the same problem on Google Chrome and Firefox, both on Linux, with latest Threema. I do not know why this issue was closed.

@sillych I have just sent my log file from the issue to Threema for analysis. I have mentioned this issue in the log description. Does that help?

**Comment by dbrgn** [comment] 2018-05-16 10:57
@emmenlau the issue was closed because connectivity problems are usually caused by the network or the smartphone OS. contacting the support is the way to go :slightly_smiling_face:

**Comment by emmenlau** [comment] 2018-05-16 11:09
Ok I contacted Threema support. Thanks for your help!

**Comment by Luckz** [comment] 2018-06-15 03:41
@emmenlau In case you did not manage to resolve it, I faintly remember having had issues like this when my uBlock Origin had WebRTC-related checkboxes ticked. Apologies if it's unrelated.
