### ISSUE TITLE
Number emojis broken

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#188] opened 2017-03-26 09:50 UTC
## Expected Behavior
Emoji displayed correctly just as in the Threema app:
![disp](https://cloud.githubusercontent.com/assets/11966684/24330216/0e92705c-121a-11e7-91ba-944b01b1d423.png)

## Current Behavior

![grafik](https://cloud.githubusercontent.com/assets/11966684/24330218/1a355960-121a-11e7-887c-8639c88583dd.png)

Strangely the numbers 8 and 9 are displayed correctly as it seems.

## Possible Solution

I don't know if this could be a fallback to a systems font or the EmojiOne included in Firefox, but if so, you could remove it so that you always render all emojis.

## Steps to Reproduce (for bugs)

1. Send `7⃣5⃣9⃣3⃣2⃣3⃣` to ECHOECHO.

## Your Environment

* Threema Web version: 1.1.0
* Threema for Android version: 3.13.20000346
* Threema for Android source: Play Store
* Browser name and version: Firefox 52.0.1
* Operating system and version: Debian 8

**Comment by dbrgn** [comment] 2017-03-26 10:39
Most probably a duplicate of (or at least closely related to) #54.

**Closed by dbrgn** 2017-03-26 10:39 UTC
