### ISSUE TITLE
Scrolling in chat shows console errors ("invalid arguments")

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#95] opened 2017-02-25 21:53 UTC
## Expected Behavior

Scrolling in chat without console errors

## Current Behavior

```
Error: invalid arguments
[77]</</<@https://web-beta.threema.ch/dist/app.js?v=1.0.3:10340:21
anonymous/fn@https://web-beta.threema.ch/node_modules/angular/angular.js?v=1.0.3 line 15126 > Function:2:333
regularInterceptedExpression@https://web-beta.threema.ch/node_modules/angular/angular.js?v=1.0.3:16354:55
expressionInputWatch@https://web-beta.threema.ch/node_modules/angular/angular.js?v=1.0.3:16256:26
$RootScopeProvider/this.$get</Scope.prototype.$digest@https://web-beta.threema.ch/node_modules/angular/angular.js?v=1.0.3:17828:34
$RootScopeProvider/this.$get</Scope.prototype.$apply@https://web-beta.threema.ch/node_modules/angular/angular.js?v=1.0.3:18102:13
timeout/timeoutId<@https://web-beta.threema.ch/node_modules/angular/angular.js?v=1.0.3:19950:25
completeOutstandingRequest@https://web-beta.threema.ch/node_modules/angular/angular.js?v=1.0.3:6045:7
Browser/self.defer/timeoutId<@https://web-beta.threema.ch/node_modules/angular/angular.js?v=1.0.3:6324:7
 angular.js:14199:18
Error: invalid arguments
[77]</</<@https://web-beta.threema.ch/dist/app.js?v=1.0.3:10340:21
anonymous/fn@https://web-beta.threema.ch/node_modules/angular/angular.js?v=1.0.3 line 15126 > Function:2:333
regularInterceptedExpression@https://web-beta.threema.ch/node_modules/angular/angular.js?v=1.0.3:16354:55
expressionInputWatch@https://web-beta.threema.ch/node_modules/angular/angular.js?v=1.0.3:16256:26
$RootScopeProvider/this.$get</Scope.prototype.$digest@https://web-beta.threema.ch/node_modules/angular/angular.js?v=1.0.3:17828:34
$RootScopeProvider/this.$get</Scope.prototype.$apply@https://web-beta.threema.ch/node_modules/angular/angular.js?v=1.0.3:18102:13
[50]</exports.default</<.controller</this.requestAvatar/<@https://web-beta.threema.ch/dist/app.js?v=1.0.3:8455:21
```

## Steps to Reproduce (for bugs)

These errors are shown when I scroll in my chat with *SUPPORT:
![errors](https://cloud.githubusercontent.com/assets/11966684/23335047/c594e318-fbac-11e6-8158-ddc606dafb58.png)

Some other contacts are also affected, but I could not conclude what exactly is causing these errors. Probably the files?
Also happens with non-Gateway-IDs.

## Your Environment

* Threema Web version: 1.0.3
* Browser name and version: Firefox 51.0.1
* Operating system and version: Debian 8

**Comment by rugk** [comment] 2017-02-25 21:56
The same error is also shown when I e.g. open the "My Threema ID" popup:

```
Error: invalid arguments
[77]</</<@https://web-beta.threema.ch/dist/app.js?v=1.0.3:10340:21
anonymous/fn@https://web-beta.threema.ch/node_modules/angular/angular.js?v=1.0.3 line 15126 > Function:2:333
regularInterceptedExpression@https://web-beta.threema.ch/node_modules/angular/angular.js?v=1.0.3:16354:55
expressionInputWatch@https://web-beta.threema.ch/node_modules/angular/angular.js?v=1.0.3:16256:26
$RootScopeProvider/this.$get</Scope.prototype.$digest@https://web-beta.threema.ch/node_modules/angular/angular.js?v=1.0.3:17828:34
$RootScopeProvider/this.$get</Scope.prototype.$evalAsync/<@https://web-beta.threema.ch/node_modules/angular/angular.js?v=1.0.3:18033:15
completeOutstandingRequest@https://web-beta.threema.ch/node_modules/angular/angular.js?v=1.0.3:6045:7
Browser/self.defer/timeoutId<@https://web-beta.threema.ch/node_modules/angular/angular.js?v=1.0.3:6324:7
  angular.js:14199:18
	consoleLog/< https://web-beta.threema.ch/node_modules/angular/angular.js:14199:18
	$ExceptionHandlerProvider/this.$get</< https://web-beta.threema.ch/node_modules/angular/angular.js:10707:7
	$RootScopeProvider/this.$get</Scope.prototype.$digest https://web-beta.threema.ch/node_modules/angular/angular.js:17854:19
	$RootScopeProvider/this.$get</Scope.prototype.$evalAsync/< https://web-beta.threema.ch/node_modules/angular/angular.js:18033:15
	completeOutstandingRequest https://web-beta.threema.ch/node_modules/angular/angular.js:6045:7
	Browser/self.defer/timeoutId< https://web-beta.threema.ch/node_modules/angular/angular.js:6324:7

```

**Comment by dbrgn** [comment] 2017-02-27 10:25
I cannot reproduce this issue. Does ist still occur?

In any case, I improved the error logging (#99). You could try current master to see if you get nicer error messages. These might help to find the root cause.

**Comment by rugk** [comment] 2017-02-27 15:42
It's still reproducible, but I can wait until the next release to test it again as it is not a big problem…

**Comment by dbrgn** [comment] 2017-05-08 11:39
I'll close this. Let us know if the problem is still here.

**Closed by dbrgn** 2017-05-08 11:39 UTC
Labels: bug, cannot reproduce
