### ISSUE TITLE
Finding of one's favorite emojis

### ISSUE THREAD

**Issue by andyggg** [threema-ch/threema-web#647] opened 2018-10-23 19:32 UTC
## Expected Behavior
Quickly find favorite emojis

## Current Behavior
All emojis are in a quite incomprehensibly long list. Makes it hard to find a specific emoji, in particular regarding frequently used emojis (one has to find it in the list over and over again)

## Possible Solution
Show favorite/frequently used emojis in a separate list. Maybe in sync with the App (don't know if that is possible, probably not).
Or introduce at least subgroups where all related emojis (same gesture, only different skin colors) are grouped together so that the menu is more tidy.

**Comment by rugk** [comment] 2018-10-23 21:19
Dupe of https://github.com/threema-ch/threema-web/issues/166(?)

**Comment by lgrahl** [comment] 2018-10-24 08:16
Agree, duplicate of #166 (but please vote for that issue with :+1: if you want it getting done sooner)

**Closed by lgrahl** 2018-10-24 08:16 UTC
