### ISSUE TITLE
White page on load (no QR code being shown)

### ISSUE THREAD

**Issue by Dionis0s** [threema-ch/threema-web#71] opened 2017-02-20 12:25 UTC
System:
Debian 8 (jessie), Firefox ESR 45.7.0, [NoScript Plugin](https://noscript.net)

Allthough NoScript is disabled for threema.ch and also for subdomain web.threema.ch, the interface 	more precisely the section with QR-Qode an so on, was not shown down.

What content will be loaded?

**Comment by dbrgn** [comment] 2017-02-20 13:43
This is most probably because you're blocking access to LocalStorage.

In Chrome, that setting can be found under Settings > Advanced > Privacy > Content Settings > Cookies.

In Firefox, it's the "dom.storage.enabled" setting in about:config.

If those settings are on their default values, it might be caused by a plugin that blocks access to local storage.

We need local storage access to persist sessions and to store user settings. All data is encrypted with the session password.

Workaround for this issue was merged this morning: #67

**Comment by Dionis0s** [comment] 2017-02-21 22:22
Now, QR-Code shown small time and I get the error-message:

> Fehler: Server-Verbindung wurde geschlossen.
> Bitte laden Sie die Seite neu.

If I reload the page, the error-message notified again.

**Comment by lgrahl** [comment] 2017-02-22 10:31
Maybe WebSocket is blocked as well?

**Comment by rugk** [comment] 2017-02-22 15:57
Independent to whether it works you should probably show an error message when local storage access failed. A white page is rather unsuitable…😁

**Comment by dbrgn** [comment] 2017-02-22 16:55
> Regardless of whether it works you should probably show an error message when local storage access failed. 

It does: #67

**Closed** 2017-02-27 16:58 UTC
Labels: bug
