### ISSUE TITLE
emoji theme

### ISSUE THREAD

**Issue by thomasoberthanner** [threema-ch/threema-web#424] opened 2018-02-10 20:49 UTC
## Expected Behavior
threema-web and app both use the same graphics for emojis 

## Current Behavior
threema-web uses other images 
android:
![threema-android-app](https://user-images.githubusercontent.com/1303299/36066508-f9d3540e-0eaa-11e8-94c6-4c9cd0d029dc.png)

threema-web
![threema-web](https://user-images.githubusercontent.com/1303299/36066509-f9ef1afe-0eaa-11e8-9c5d-f24ca01971e7.png)

## Possible Solution
update png files in public/img/e1

## Your Environment

* Threema Web version: 1.7.0
* Threema for Android version:3.31.2000394
* Threema for Android source: Play Store
* Browser name and version: Chromium Version 64.0.3282.119 (Entwickler-Build) (64-Bit)
* Operating system and version: Antergos

**Comment by dbrgn** [comment] 2018-02-10 20:54
Thanks for the report. This is a duplicate of #146, see [this comment](https://github.com/threema-ch/threema-web/issues/146#issuecomment-285067020).

**Closed by dbrgn** 2018-02-10 20:54 UTC
