### ISSUE TITLE
Show icon/avatar for distribution list

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#464] opened 2018-03-02 18:03 UTC
## Expected Behavior
Same style in app and Threema Web

## Current Behavior
No icon/avatar for distribution list in Threema Web

Android app:
![screenshot_20180302-190032](https://user-images.githubusercontent.com/8258609/36914057-3d57a8c8-1e4c-11e8-9a2e-878403dd2cea.png)

Threema Web:
![screenshot-2018-3-2 threema web](https://user-images.githubusercontent.com/8258609/36914091-5820917e-1e4c-11e8-849f-b20830fecc7d.png)

## Your Environment
* Threema Web version: 1.8.2
* Threema for Android version: 3.4
* Browser name and version: Firefox 58.0.2

**Comment by IndianaDschones** [comment] 2018-03-12 12:17
@dbrgn I debugged the avatar directive to see why the avatar is not set for distribution lists.

The `receiver.avatar["low"]` property is `""`.
![testliste](https://user-images.githubusercontent.com/6652142/37283248-94892dda-25f7-11e8-816e-acc6b34267cd.PNG)
So the avatar is defined, but empty. I think it may be an app-side problem (avatar not sent) or sth. If it is client-side, can you give me a hint where the avatar may be set to `""` so that i can solve this?

**Comment by dbrgn** [comment] 2018-03-12 12:57
Actually I cannot reproduce this...

![screenshot](https://tmp.dbrgn.ch/screenshots/20180312134141-vzre6dej.png)

@IndianaDschones can you reproduce it? did you do something special with that distribution list?

**Comment by dbrgn** [comment] 2018-03-12 13:01
Ah, I could reproduce it with a newly created distribution list :) Yes, if the avatar is empty that's a problem on the app side.

**Comment by dbrgn** [comment] 2018-03-12 14:54
@IndianaDschones it's a problem on both sides. the app will get a fix in the next app release. however, I implemented a workaround in #473.

**Comment by dbrgn** [comment] 2018-03-12 14:55
If one of @IndianaDschones or @ovalseven8 could test whether the distribution list avatars load correctly on the `464-avatar-null` branch, that would be great :)

**Comment by IndianaDschones** [comment] 2018-03-12 15:17
The color is different (pink instead of blue) but in general it works 😉

**Comment by dbrgn** [comment] 2018-03-12 15:38
Yes, the reason for that is in the app and will also be fixed in the next release :)

**Closed** 2018-03-12 15:48 UTC
Labels: app-update, bug

**Comment by IndianaDschones** [comment] 2018-03-13 09:30
@dbrgn Works as intended in the latest beta 👍

**Comment by dbrgn** [comment] 2018-03-13 09:43
Great to hear :slightly_smiling_face:
