### ISSUE TITLE
Scrolling with mouse wheel does not work properly in chat window

### ISSUE THREAD

**Issue by simonschaufi** [threema-ch/threema-web#137] opened 2017-03-06 23:02 UTC
## Expected Behavior
Scrolling with the mouse wheel in the chat windows scrolls to old chat messages (always!)

## Current Behavior
I haven't figured it out when scrolling works but most of the time nothing is scrolling. When I scroll up and down, the "arrow icon" to scroll down appear and disappear and when there is a picture, it looks like the pic is loaded again and again (become sharp and unsharp).
The moment I "broke out" of being stuck at the bottom i can scroll easily and load all the old history

## Possible Solution
I don't even see a scrollbar...

## Steps to Reproduce (for bugs)
1. click on contact to start chatting
2. scroll up to load old history

## Your Environment
* Threema Web version: Version 1.0.5
* Browser name and version: SRWare Iron / Google Chrome 55
* Operating system and version: Windows 7 (but shouldn't matter)

**Comment by dbrgn** [comment] 2017-03-07 08:44
Duplicate of #18.

**Closed by dbrgn** 2017-03-07 08:44 UTC
