### ISSUE TITLE
Threema app corrupted probably because of Threema Web

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#269] opened 2017-07-17 13:34 UTC
Today I updated my Threema app to the latest version (3.15) and I tested Threema Web.
Unfortunately, it seems like there is a major bug in the latest Threema app version.

I logged into my Threema Web session and after a few seconds the login was successful. Then I logged out and tried to login again. Unfortunately, the login was unsuccessful then although I tried it several times.

So I grabbed my smartphone because sometimes it helps to touch it but it also did not work. Then I unlocked it because I wanted to open the Threema app (perhaps it helps I thought).
When I tried to open Threema, this screen was displayed:
https://user-images.githubusercontent.com/8258609/28269793-9185a974-6b03-11e7-85f5-d7e5658c2007.png

Then I opened the menu:
https://user-images.githubusercontent.com/8258609/28269877-d522c4e6-6b03-11e7-9cd2-1e204be842f0.png
Note here: Wrong Threema ID, no avatar!

Then I opened my Threema contact list:
https://user-images.githubusercontent.com/8258609/28270011-42692158-6b04-11e7-8a01-11e3a3a4dd7a.png
Note here: No avatars!

Finally, I thought to send message_log.txt to you immediately. But it did not work too although I waited for about a minute (the size is ~1.2 MB):
https://user-images.githubusercontent.com/8258609/28270089-8a1ae220-6b04-11e7-823d-81c3c5a9cd5a.png

When I tried to close Threema and open again, the bug did not disappear.
The good message: After rebooting the smartphone, everything seems to be normal again. :smile: 

Here the perhaps relevant `message_log.txt`:
[message_log.txt](https://github.com/threema-ch/threema-web/files/1152757/message_log.txt)

## Your Environment
* Threema Web version: 1.3.1
* Threema for Android version: 3.15.2000354
* Threema for Android source: Play Store
* Browser name and version: Firefox 54.0
* Operating system and version: Lubuntu 16.04

**Comment by dbrgn** [comment] 2017-07-17 14:18
Hm, I never saw that before. I could not reproduce it either.

The bug hasn't happened again since, right?

**Comment by ovalseven8** [comment] 2017-07-17 14:34
> The bug hasn't happened again since, right?
Not yet.

**Comment by dbrgn** [comment] 2017-07-20 09:33
Hm, since we could not reproduce this and since it didn't happen again, I hope it was a one-off thing.

I'll close this issue for now. In case the problem persists, comments are still open.

**Comment by ovalseven8** [comment] 2017-07-20 12:04
I could reproduce it just now!

**Comment by dbrgn** [comment] 2017-07-20 12:11
What smartphone model do you have, with which Android version?

**Comment by ovalseven8** [comment] 2017-07-20 12:18
Unfortunately, there is nothing interesting in the `message_log.txt` file for the time the bug occurred. At least, the log looks the same as in the starting post.

However, there are some Exceptions in the log about 30 minutes to 1 hour before the bug occurred. No idea if it perhaps has something to do with it.

My smartphone: Motorola Moto E 2nd Generation (4G LTE) with Android 6.0
```
Thu Jul 20 12:06:12 GMT+02:00 2017	cleanupConnection: connection must linger for another 59967 milliseconds
Thu Jul 20 12:06:51 GMT+02:00 2017	java.lang.NullPointerException: Attempt to read from field 'bhi bfc.b' on a null object reference
	at aac$9.a(SourceFile:1119)
	at yi$3.a(SourceFile:1218)
	at oa$b.a(SourceFile:81)
	at yi.a(SourceFile:3215)
	at yi$a.onIceConnectionChange(SourceFile:264)

Thu Jul 20 12:07:01 GMT+02:00 2017	java.lang.NullPointerException: Attempt to read from field 'bhi bfc.b' on a null object reference
	at aac$9.a(SourceFile:1119)
	at yi$3.a(SourceFile:1218)
	at oa$b.a(SourceFile:81)
	at yi.a(SourceFile:3215)
	at yi$a.onIceConnectionChange(SourceFile:267)

Thu Jul 20 12:07:12 GMT+02:00 2017	AlarmManagerBroadcastReceiver: onReceive
Thu Jul 20 12:07:12 GMT+02:00 2017	Alarm (1)
Thu Jul 20 12:07:12 GMT+02:00 2017	stopConnection
Thu Jul 20 12:07:12 GMT+02:00 2017	ThreemaConnection state changed: DISCONNECTED Port: 5222 IPv6: false
Thu Jul 20 12:07:12 GMT+02:00 2017	cleanupConnection: connection closed
Thu Jul 20 12:11:21 GMT+02:00 2017	Enqueue delivery receipt (user ack) message ID ANONYMIZED for message ID ANONYMIZED from ANONYMIZED
Thu Jul 20 12:11:23 GMT+02:00 2017	Enqueue delivery receipt (user dec) message ID ANONYMIZED for message ID ANONYMIZED from ANONYMIZED
Thu Jul 20 12:11:26 GMT+02:00 2017	Enqueue delivery receipt (user ack) message ID ANONYMIZED for message ID ANONYMIZED from ANONYMIZED
Thu Jul 20 12:15:05 GMT+02:00 2017	acquireConnection: source = activityResumed, refCount = 1
Thu Jul 20 12:15:05 GMT+02:00 2017	startConnection
Thu Jul 20 12:15:05 GMT+02:00 2017	ThreemaConnection state changed: CONNECTING Port: 5222 IPv6: false
Thu Jul 20 12:15:05 GMT+02:00 2017	ThreemaConnection state changed: CONNECTED Port: 5222 IPv6: false
Thu Jul 20 12:15:05 GMT+02:00 2017	ThreemaConnection state changed: LOGGEDIN Port: 5222 IPv6: false
Thu Jul 20 12:15:06 GMT+02:00 2017	process ACK for message ANONYMIZED
Thu Jul 20 12:15:06 GMT+02:00 2017	process ACK for message ANONYMIZED
Thu Jul 20 12:15:06 GMT+02:00 2017	process ACK for message ANONYMIZED
Thu Jul 20 12:15:25 GMT+02:00 2017	releaseConnectionLinger: source = activityPaused, timeout = 60000
Thu Jul 20 12:15:25 GMT+02:00 2017	Cancel Alarm 1
Thu Jul 20 12:15:25 GMT+02:00 2017	Schedule alarm 1 in 59997ms
Thu Jul 20 12:15:25 GMT+02:00 2017	releaseConnection: source = activityPaused, refCount = 0
Thu Jul 20 12:15:25 GMT+02:00 2017	cleanupConnection: connection must linger for another 59995 milliseconds
Thu Jul 20 12:15:26 GMT+02:00 2017	*** App UI is hidden
Thu Jul 20 12:15:26 GMT+02:00 2017	onTrimMemory: 20
Thu Jul 20 12:15:27 GMT+02:00 2017	acquireConnection: source = activityResumed, refCount = 1
Thu Jul 20 12:15:27 GMT+02:00 2017	connection already active
Thu Jul 20 12:15:29 GMT+02:00 2017	java.lang.NullPointerException: Attempt to read from field 'bhi bfc.b' on a null object reference
	at aac$9.a(SourceFile:1119)
	at yi$3.a(SourceFile:1218)
	at oa$b.a(SourceFile:81)
	at yi.a(SourceFile:3215)
	at yi$a.onIceConnectionChange(SourceFile:264)

Thu Jul 20 12:15:39 GMT+02:00 2017	java.lang.NullPointerException: Attempt to read from field 'bhi bfc.b' on a null object reference
	at aac$9.a(SourceFile:1119)
	at yi$3.a(SourceFile:1218)
	at oa$b.a(SourceFile:81)
	at yi.a(SourceFile:3215)
	at yi$a.onIceConnectionChange(SourceFile:267)

Thu Jul 20 12:16:05 GMT+02:00 2017	releaseConnectionLinger: source = activityPaused, timeout = 60000
Thu Jul 20 12:16:05 GMT+02:00 2017	Cancel Alarm 1
Thu Jul 20 12:16:05 GMT+02:00 2017	Schedule alarm 1 in 59978ms
Thu Jul 20 12:16:05 GMT+02:00 2017	releaseConnection: source = activityPaused, refCount = 0
Thu Jul 20 12:16:05 GMT+02:00 2017	cleanupConnection: connection must linger for another 59973 milliseconds
Thu Jul 20 12:17:05 GMT+02:00 2017	AlarmManagerBroadcastReceiver: onReceive
Thu Jul 20 12:17:05 GMT+02:00 2017	Alarm (1)
Thu Jul 20 12:17:05 GMT+02:00 2017	stopConnection
Thu Jul 20 12:17:05 GMT+02:00 2017	ThreemaConnection state changed: DISCONNECTED Port: 5222 IPv6: false
Thu Jul 20 12:17:05 GMT+02:00 2017	cleanupConnection: connection closed
Thu Jul 20 12:21:08 GMT+02:00 2017	Handling incoming GCM intent.
Thu Jul 20 12:21:08 GMT+02:00 2017	Received GCM webclient wakeup for session ANONYMIZED
Thu Jul 20 12:21:32 GMT+02:00 2017	java.lang.NullPointerException: Attempt to read from field 'bhi bfc.b' on a null object reference
	at aac$9.a(SourceFile:1119)
	at yi$3.a(SourceFile:1218)
	at oa$b.a(SourceFile:81)
	at yi.a(SourceFile:3215)
	at yi$a.onIceConnectionChange(SourceFile:264)

Thu Jul 20 12:21:42 GMT+02:00 2017	java.lang.NullPointerException: Attempt to read from field 'bhi bfc.b' on a null object reference
	at aac$9.a(SourceFile:1119)
	at yi$3.a(SourceFile:1218)
	at oa$b.a(SourceFile:81)
	at yi.a(SourceFile:3215)
	at yi$a.onIceConnectionChange(SourceFile:267)

Thu Jul 20 12:57:13 GMT+02:00 2017	acquireConnection: source = activityResumed, refCount = 1
Thu Jul 20 12:57:13 GMT+02:00 2017	startConnection
Thu Jul 20 12:57:14 GMT+02:00 2017	ThreemaConnection state changed: CONNECTING Port: 5222 IPv6: false
Thu Jul 20 12:57:14 GMT+02:00 2017	ThreemaConnection state changed: CONNECTED Port: 5222 IPv6: false
Thu Jul 20 12:57:14 GMT+02:00 2017	ThreemaConnection state changed: LOGGEDIN Port: 5222 IPv6: false
Thu Jul 20 12:57:14 GMT+02:00 2017	java.lang.NullPointerException: Attempt to read from field 'bhi bfc.b' on a null object reference
	at aac$9.a(SourceFile:1119)
	at yi$3.a(SourceFile:1218)
	at oa$b.a(SourceFile:81)
	at yi.a(SourceFile:3215)
	at yi$a.onIceConnectionChange(SourceFile:264)

Thu Jul 20 12:57:16 GMT+02:00 2017	releaseConnectionLinger: source = activityPaused, timeout = 60000
Thu Jul 20 12:57:16 GMT+02:00 2017	Cancel Alarm 1
Thu Jul 20 12:57:16 GMT+02:00 2017	Schedule alarm 1 in 59994ms
Thu Jul 20 12:57:16 GMT+02:00 2017	releaseConnection: source = activityPaused, refCount = 0
Thu Jul 20 12:57:16 GMT+02:00 2017	cleanupConnection: connection must linger for another 59991 milliseconds
Thu Jul 20 12:57:16 GMT+02:00 2017	*** App UI is hidden
Thu Jul 20 12:57:16 GMT+02:00 2017	onTrimMemory: 20
Thu Jul 20 12:57:19 GMT+02:00 2017	acquireConnection: source = activityResumed, refCount = 1
Thu Jul 20 12:57:19 GMT+02:00 2017	connection already active
Thu Jul 20 12:57:24 GMT+02:00 2017	java.lang.NullPointerException: Attempt to read from field 'bhi bfc.b' on a null object reference
	at aac$9.a(SourceFile:1119)
	at yi$3.a(SourceFile:1218)
	at oa$b.a(SourceFile:81)
	at yi.a(SourceFile:3215)
	at yi$a.onIceConnectionChange(SourceFile:267)

Thu Jul 20 12:57:33 GMT+02:00 2017	java.lang.NullPointerException: Attempt to read from field 'bhi bfc.b' on a null object reference
	at aac$9.a(SourceFile:1119)
	at yi$3.a(SourceFile:1218)
	at oa$b.a(SourceFile:81)
	at yi.a(SourceFile:3215)
	at yi$a.onIceConnectionChange(SourceFile:264)

Thu Jul 20 12:57:43 GMT+02:00 2017	java.lang.NullPointerException: Attempt to read from field 'bhi bfc.b' on a null object reference
	at aac$9.a(SourceFile:1119)
	at yi$3.a(SourceFile:1218)
	at oa$b.a(SourceFile:81)
	at yi.a(SourceFile:3215)
	at yi$a.onIceConnectionChange(SourceFile:267)

Thu Jul 20 12:58:16 GMT+02:00 2017	AlarmManagerBroadcastReceiver: onReceive
Thu Jul 20 12:58:16 GMT+02:00 2017	Alarm (1)
Thu Jul 20 12:58:25 GMT+02:00 2017	java.lang.NullPointerException: Attempt to read from field 'bhi bfc.b' on a null object reference
	at aac$9.a(SourceFile:1119)
	at yi$3.a(SourceFile:1218)
	at oa$b.a(SourceFile:81)
	at yi.a(SourceFile:3215)
	at yi$a.onIceConnectionChange(SourceFile:264)

Thu Jul 20 12:58:35 GMT+02:00 2017	java.lang.NullPointerException: Attempt to read from field 'bhi bfc.b' on a null object reference
	at aac$9.a(SourceFile:1119)
	at yi$3.a(SourceFile:1218)
	at oa$b.a(SourceFile:81)
	at yi.a(SourceFile:3215)
	at yi$a.onIceConnectionChange(SourceFile:267)
```

**Comment by dbrgn** [comment] 2017-07-20 12:22
Were these errors immediately before the reconnect failed?

**Comment by ovalseven8** [comment] 2017-07-20 12:52
More or less. In the log the error is about 40 minutes before I wanted to login to the session.

```
Thu Jul 20 13:02:43 GMT+02:00 2017	Received GCM webclient wakeup for session 9a184a116b5405a04f883b051e143343152b581c0740bf9747876262d5105735
Thu Jul 20 13:16:07 GMT+02:00 2017	java.lang.NullPointerException: Attempt to read from field 'bhi bfc.b' on a null object reference
	at aac$9.a(SourceFile:1119)
	at yi$3.a(SourceFile:1218)
	at oa$b.a(SourceFile:81)
	at yi.a(SourceFile:3215)
	at yi$a.onIceConnectionChange(SourceFile:264)

Thu Jul 20 13:21:45 GMT+02:00 2017	java.lang.NullPointerException: Attempt to read from field 'bhi bfc.b' on a null object reference
	at aac$9.a(SourceFile:1119)
	at yi$3.a(SourceFile:1218)
	at oa$b.a(SourceFile:81)
	at yi.a(SourceFile:3215)
	at yi$a.onIceConnectionChange(SourceFile:267)
```

And now I wanted to login to the session. **There is nothing left out. Between 13:21:45 and 14:00:51 there is no log message.**
```
Thu Jul 20 14:00:51 GMT+02:00 2017	Handling incoming GCM intent.
Thu Jul 20 14:00:51 GMT+02:00 2017	Received GCM webclient wakeup for session 9a184a116b5405a04f883b051e143343152b581c0740bf9747876262d5105735
Thu Jul 20 14:01:05 GMT+02:00 2017	Handling incoming GCM intent.
Thu Jul 20 14:01:05 GMT+02:00 2017	Received GCM webclient wakeup for session 9a184a116b5405a04f883b051e143343152b581c0740bf9747876262d5105735
Thu Jul 20 14:01:07 GMT+02:00 2017	Handling incoming GCM intent.
Thu Jul 20 14:01:07 GMT+02:00 2017	Received GCM webclient wakeup for session 9a184a116b5405a04f883b051e143343152b581c0740bf9747876262d5105735
Thu Jul 20 14:03:06 GMT+02:00 2017	Handling incoming GCM intent.
Thu Jul 20 14:03:06 GMT+02:00 2017	Received GCM webclient wakeup for session 9a184a116b5405a04f883b051e143343152b581c0740bf9747876262d5105735
Thu Jul 20 14:03:18 GMT+02:00 2017	Handling incoming GCM intent.
Thu Jul 20 14:03:18 GMT+02:00 2017	Received GCM webclient wakeup for session 9a184a116b5405a04f883b051e143343152b581c0740bf9747876262d5105735
Thu Jul 20 14:03:40 GMT+02:00 2017	Handling incoming GCM intent.
```

**Comment by ovalseven8** [comment] 2017-07-20 13:00
Thing is, the first time I produced this bug there haven't been those errors in the log before I tried to connect to the session. Also while browsing through the log I noticed that there were those Exceptions also in June already.

But nonetheless, perhaps it has something to do with it and you can fix it.

**Comment by ovalseven8** [comment] 2017-08-05 16:01
Could you already identify the problem?

**Comment by dbrgn** [comment] 2017-08-05 20:34
Not really. It's probably a deadlock that caused the app initialization to hang. The ID "ABCDEFGH" is the "default ID" that is shown before the real ID is loaded.

The next app release will contain a refactoring of the Threema Web state handling, that might solve the problem. I'll close this for now, but let me know if it reappears in the next app version.

**Comment by ovalseven8** [comment] 2017-09-10 13:54
@dbrgn: Now, I've found a similar issue and can reproduce it.

Before trying to reproduce send a video (my video has ~25 MB) to a contact.
Now do a reboot or just close the Threema app.

To reproduce do the following:
1. Reconnect to a Threema Web session
2. Go to the conversation with the video inside Threema Web
3. Click on the three dots and "Download" (![2017-09-10-155252_1920x1080_scrot](https://user-images.githubusercontent.com/8258609/30249639-51edc6c6-9640-11e7-8fb8-0ed49154c705.png))

4. Open Threema app
5. Now you should be able to reproduce the issue mentioned above. However, in this example this issue disappears after the download has been successful.

**Comment by dbrgn** [comment] 2017-09-11 08:06
@ovalseven8 thanks, I can reproduce this issue now!

**Comment by ovalseven8** [comment] 2018-01-28 09:07
So you can remove the label "Cannot reproduce" 😄

**Comment by lgrahl** [comment] 2019-05-03 10:48
@dbrgn Is this still a thing?

**Comment by dbrgn** [comment] 2019-05-06 14:52
I just checked, yep. I'll try to tackle it this week, it's a threading issue in the app.

**Comment by dbrgn** [comment] 2019-05-08 08:27
The issue with the profile not being loaded (identity shown as ABCDEFGH) should be fixed in the next version of the Android app. It's still possible that avatars are slow to load when starting the app while a download is in progress in Threema Web, but that should not impair usage of the app.

**Closed by dbrgn** 2019-05-08 08:27 UTC
Labels: bug
