### ISSUE TITLE
Show Web-/SaltyRTC connection details in Threema

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#195] opened 2017-04-10 08:33 UTC
User story: I, as a (heavy) Threema Web user, want to see what route the Threema Web connection uses (mobile data/WiFi, uses TURN?) in order to evaluate problems/slowness/security/high costs…

This helps to:
* avoid high costs when users have limited mobile data plans
* evaluate the security (TURN is probably not what I want to use)
* find reasons for slowness ("ah, mobile data and TURN, …") or disconnections ("oh, just switched to TURN")
* potentially debug things (when you can also see what TURN mode is used – in a submenu, of course)

### Potential solution
Display an icon in the "Threema Web" panel in the Threema app showing a basic connection status. And maybe add a context item ("Connection details" or the like) where advanced users can see a more detailed status. (maybe even with connection duration or so)

**Comment by dbrgn** [comment] 2017-04-10 08:43
Duplicate of #13.

**Closed by dbrgn** 2017-04-10 08:43 UTC

**Comment by rugk** [comment] 2017-04-10 08:56
Upps, too stupid… :laughing:
