### ISSUE TITLE
Laggy input

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#480] opened 2018-03-29 11:57 UTC
## Expected Behavior
No input latency.

## Current Behavior
Laggy input.

## Steps to Reproduce (for bugs)
1. Go to https://pixabay.com/de/s%C3%A4ugetiere-wildlife-teuer-fox-3218028/
2. Right click -> Copy image
3. Go to a Threema Web conversation (e.g. ECHOECHO)
4. Paste image using Ctrl+V
5. Write something in the image description (type fast, so the problem is more visible)
6. Extremely laggy input

Now try the following:

1. Go to https://de.wikipedia.org/wiki/Threema#/media/File:Threema.png
2. Right click -> Copy image
3. Go to a Threema Web conversation (e.g. ECHOECHO)
4. Paste image using Ctrl+V
5. Write something and you should notice that the input is faster now. So it seems like it has something to do with the media (perhaps media size?).

## Your Environment
* Threema Web version: 1.8.2
* Threema for Android version: 3.41
* Browser name and version: Firefox 59.0.2

**Comment by dbrgn** [comment] 2018-03-29 14:10
Thanks for the detailed description, I can confirm the problem.

**Comment by LtPatterson** [comment] 2018-04-04 17:11
Also able to duplicate in Chrome 65

**Comment by dbrgn** [comment] 2018-07-02 16:00
Very slow key and input event handling, time increasing with media size:

![img](https://tmp.dbrgn.ch/screenshots/20180702172134-pxchj04e.png)

The key event takes 124ms to process. After some debugging, it turns out that the `bufferToUrl` filter is called dozens or even hundreds of times when typing.

Pre-converting the buffer to an URI reduced key event handling times down to 14ms.

![img](https://tmp.dbrgn.ch/screenshots/20180702175732-a54wo8da.png)

Further optimizations in the codebase are possible and planned.

Main issue fixed in the `ios` branch as of commit ca93785822e3b82cfa47ae60b20162cbeef14326.

**Closed by dbrgn** 2018-07-02 16:00 UTC
Labels: bug, performance
