### ISSUE TITLE
Selfhosting in subdir breaks Emojis

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#747] opened 2019-01-30 19:34 UTC
## Expected Behavior

Emoji categories correctly shown.

## Current Behavior

![image](https://user-images.githubusercontent.com/11966684/52007116-1c68bd80-24ce-11e9-950e-713db73fba81.png)

## Possible Solution

You assume an absolute path, where no absolute path can be assumed.

Because it does request e.g. `/emoji/people.svg`, where it should actually request `/subdir/emoji/people.svg` (i.e. `./emoji/people.svg`).

## Steps to Reproduce (for bugs)

1. Self-host with `/somesubdir`.

## Your Environment

* Threema Web version: v2.1.5 (this issue was introduced with v2.1.5)

**Comment by rugk** [comment] 2019-01-30 20:30
Also the inline conversion of Emojis is broken. It likewise requests `/emoji/png32/1f606.png` here, missing the subdir…

**Comment by lgrahl** [comment] 2019-01-30 22:59
Duplicate of #742. If it's still an issue, we can reopen it.

**Closed by lgrahl** 2019-01-30 22:59 UTC
Labels: duplicate

**Comment by dbrgn** [comment] 2019-01-31 07:59
There will be a new release today.
