### ISSUE TITLE
Strange font rendering (Roboto font)

### ISSUE THREAD

**Issue by powerriegel** [threema-ch/threema-web#960] opened 2020-01-18 09:09 UTC
## Bug Description
The contact list in Threema Web (Beta tested, too) has a very ugly font rendering issue. the letter "a" is filled at the top and the whole text is blurry. No additional fonts installed. The chat itself looks good and perfectly sharp. No zoom (Ctrl-0), did not change DPI. Other websites looks great. 

Ubuntu 19.10 on nVidia Graphics in Full HD. Kubuntu is affected, too. 

![Bildschirmfoto vom 2020-01-18 10-02-07](https://user-images.githubusercontent.com/11870663/72661432-431f4d00-39da-11ea-9317-6786b7c66862.png)

(Image is resized here, download it and view at 100% size)

If I disable `font-weight: bold` it looks good again. Same when I switch to `font-family: Arial`. So, it seems to be an issue with `Roboto` font. 

* Threema Web version: Production and current beta
* Threema App version: 4.22
* Browser name and version: Firefox 72.0.1
* Computer operating system and version: Ubuntu 19.10
* Smartphone operating system and version: Android 9

P.S. On **Windows 10**  on Firefox, the chat text is blurred, too. Switching the front from Roboto to another font helps. 

It seems that the Roboto webfont is broken or not compatible with OSes anti-aliasing.

**Comment by lgrahl** [comment] 2020-01-20 10:07
I can't reproduce this atm (or I'm not seeing it).

**Comment by powerriegel** [comment] 2020-01-20 10:12
On my work PC (Ubuntu), it looks fine, too. Maybe it's related to nVidia GPU? Or to my external display?

**Comment by dbrgn** [comment] 2020-01-20 10:25
I can't reproduce it either (Linux, Nvidia). What Nvidia driver are you using?

**Comment by lgrahl** [comment] 2020-01-20 10:26
Well, if it can also be reproduced in Windows, it can't be the driver. I'm also on a nVidia card here and I'm not seeing it.

**Comment by dbrgn** [comment] 2020-01-20 10:32
Maybe you can open `about:config` in your Firefox installation, and check whether any of the options containing "gfx" are set to non-standard values (indicated in bold).

**Comment by powerriegel** [comment] 2020-01-20 18:24
I disabled all gfx settings in Firefox. Problem persists. But it's caused by the graphics hardware or the driver, as it's only visible on my external monitor. Moving the Threema Web Windows to the internal monitor solves the blurry fonts. 

Any idea what could cause this (Windows **and** Linux)?

**Comment by lgrahl** [comment] 2020-01-20 18:42
Is the image you've posted a screenshot or does it come from a camera?

**Comment by powerriegel** [comment] 2020-01-21 07:26
It's a screenshot.

**Comment by dbrgn** [comment] 2020-01-21 08:21
> But it's caused by the graphics hardware or the driver, as it's only visible on my external monitor. Moving the Threema Web Windows to the internal monitor solves the blurry fonts.

Maybe your monitor has some kind of "enhance readability" setting or something like that.

In any case, since this doesn't seem to have anything to do with Threema Web, I'll close this issue. To try to solve it, maybe search the internet for "webfont blurry", or something like that.

You can also check whether the font is also blurry here: https://fonts.google.com/specimen/Roboto

**Closed by dbrgn** 2020-01-21 08:21 UTC
Labels: awaiting triage, bug
