### ISSUE TITLE
Load chat images on demand

### ISSUE THREAD

**Issue by dns2utf8** [threema-ch/threema-web#589] opened 2018-09-17 15:44 UTC
## Expected Behavior

Have a button to fetch the images on demand in the web UI.

## Current Behavior

There is a empty box. One has to unlock the app on the phone and fetch the picture there.

## Possible Solution

A button as in the app aka. the picture-on-demand-button-protocol (podbp).

## Steps to Reproduce (for bugs)

1. Set the app to not automatically download the pictures
2. Have somebody to send you a picture.
3. ...
4. "Profit!"

## Your Environment

* Threema Web version: 2.0.3
* Threema App version: latest
* Browser name and version: latest Firefox
* Computer operating system and version: Arch Linux
* Smartphone operating system and version: Android 7.1

Cheers

**Comment by rugk** [comment] 2018-09-17 15:59
dupe of https://github.com/threema-ch/threema-web/issues/485

**Comment by dbrgn** [comment] 2018-09-17 16:44
> dupe of #485

Yep :slightly_smiling_face:

**Closed by dbrgn** 2018-09-17 16:44 UTC
