### ISSUE TITLE
Images should not be downloaded but displayed

### ISSUE THREAD

**Issue by willnix** [threema-ch/threema-web#81] opened 2017-02-21 18:03 UTC
## Expected Behavior
When clicking on images they should be displayed in the browser.
Preferably in and overlay but a new tab would also be acceptable.

## Current Behavior
Images will be downloaded every time one tries to view them in full resolution.

## Possible Solution
Setting the images mime type when saving them as blobs should enable the browser to open them as "blob:..." URLs later.
Change this:
https://github.com/threema-ch/threema-web/blob/4388e93c1d7fae7de13c28f6ee10a571d6d7f1b2/src/directives/message.ts#L112
to something like:
```js
saveAs(new Blob([buffer], {type: 'image/jpeg'}), 'image.jpg', );
```
might be sufficient  to have the browser display images in a tab.

## Steps to Reproduce (for bugs)
1. Send an Image to ECHOECHO
2. Click on the Image in the reply 

## My Environment
* Threema Web version: Version 1.0.2
* Browser name and version: Chromium

**Comment by lgrahl** [comment] 2017-02-21 19:40
Probably a duplicate of #11 but maybe you can post your suggestion there if you think it would be a more adequate solution.

**Comment by dbrgn** [comment] 2017-02-21 21:29
That's a good point, I didn't know about the blob URLs. But a image preview is planned anyways, so I'll close this in favor of #11. Thanks anyways for a nice report!

**Closed by dbrgn** 2017-02-21 21:29 UTC

**Comment by willnix** [comment] 2017-02-22 10:47
Oops, I overlooked #11  ...
Looking forward to the overlay solution! :)

**Comment by Buddabread** [comment] 2017-03-10 16:05
Would be nice to have a simple mediaplayer (Video, Picture, Music) for the common files without promt to open or save the file. This would strongly increase the usabilty of Threema-App.
