### ISSUE TITLE
Stuck at 12% Waiting for app wakeup...

### ISSUE THREAD

**Issue by fichtennadel** [threema-ch/threema-web#171] opened 2017-03-14 14:30 UTC
## Expected Behavior
Threema web should be able to reconnect to the app, if the app is running and having web enabled.

## Current Behavior
Threema web is stuck at 12% "Waiting for app wakeup..." intermittently. Sometime reconnect works, sometimes not. 
Reloading the page helps, without doing anything in the app. So I guess this is related to Threema web only.

## Steps to Reproduce
1. Connect to Threema Web session, conversations view
2. Wait (browser in background / not used)
3. When switching back to browser after some time: stuck at 12%

## Your Environment
* Threema Web version: 1.0.5
* Threema for Android version: 3.11.20000344
* Threema for Android source: Play Store
* Browser name and version: FF 52.0 and Chrome 56.0.2924.87
* Operating system and version: Win7 64bit
* WebRTC: using STUN/TURN, `turn.threema.ch:56608/udp(relayed-tcp)	<local-ip>:35637/udp(serverreflexive)`

**Comment by dbrgn** [comment] 2017-03-14 14:37
Duplicate of #106.

Next release of web / app should improve things.

**Closed by dbrgn** 2017-03-14 14:37 UTC

**Comment by tvogel** [comment] 2018-07-18 14:29
For me, this still often happens. It sometimes but not always helps to stop and restart the web session from the app. Sometimes, reloading the web page helps.

**Comment by yuemeier** [comment] 2022-05-09 17:20
Have the same issue... in 2022.

**Comment by ddBenny** [comment] 2022-05-25 06:43
Same here, fixed background execution and background data but still...

**Comment by lgrahl** [comment] 2022-05-29 00:00
Speaking for Threema Web for Android here: We hear you but the code that is under our own control has become quite robust over the last four years. FCM push **and** the Android OS on the other hand are not under our control. It's infuriatingly frustrating when a push simply does not arrive and we literally can't do anything about it.

And that is (also) why we are replacing Threema Web with a new solution as mentioned in the readme. See also #996.
