### ISSUE TITLE
Add: Contact is writing status

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#476] opened 2018-03-19 19:46 UTC
The "status" "… is writing." should be added, so I can see when someone writes a message.

It should also be shown in the contacts overview, as it is done in the Threema app.

**Comment by dbrgn** [comment] 2018-03-21 15:20
There should be a typing indicator in a chat bubble, but apparently it's a bit buggy.

Will be fixed by #475.

**Comment by rugk** [comment] 2018-03-21 17:21
What about:
> It should also be shown in the contacts overview, as it is done in the Threema app.

?

**Comment by dbrgn** [comment] 2018-03-21 17:40
That's already implemented since the first release. It shows up if the typing bubble shows up too.

**Comment by rugk** [comment] 2018-03-21 22:36
Hmm, did not happen in my case AFAIK. It still showed the text of the last message in the overview there. (maybe it's affected by the same bug as the main display though.)

**Closed** 2018-08-02 14:46 UTC
Labels: bug

**Comment by ovalseven8** [comment] 2019-01-31 20:56
Does the "... is typing" notification work for you at the moment?

**Comment by rugk** [comment] 2019-02-01 07:12
I don't remember it, but I also have not paid attention to it. How is your experience, @ovalseven8?

**Comment by ovalseven8** [comment] 2019-02-01 13:54
Yesterday, while a friend was typing it did not display "is typing ..." for me. So I wonder if this feature is broken at the moment?

**Comment by dbrgn** [comment] 2019-02-04 08:40
Maybe your app was not connected to Threema Servers. Typing indicator messages don't currently trigger a push notification to the receiver's phone. This decision was done back when there was no Threema Web, since typing notifications are useless to you if your app is not in the foreground anyways.

**Comment by ovalseven8** [comment] 2019-02-04 16:54
So, is not that behaviour "wrong" with Threema Web now?

**Comment by dbrgn** [comment] 2019-02-05 14:55
Might be, depending on how high the expectations against those messages are.

The problem is: The push server cannot know whether or not the user uses Threema Web, so pushing will have a negative power consumption impact for *all* users, no matter whether they use Threema Web or not. That's a tradeoff we have to consider.

**Comment by ovalseven8** [comment] 2019-02-05 15:00
@dbrgn: Personally, I do not have a problem if Threema Web does not support the "is typing ..." indicator at all. IMHO it's better to not support it instead of the "broken" situation right now. What do you think?

**Comment by dbrgn** [comment] 2019-02-06 13:17
@ovalseven8 it's not just "is typing", but also the "read" status update and a few other message types. we discussed another solution today that should resolve this, by allowing the app to override push settings on the server. it'll be implemented in the coming months on app/server side.
