### ISSUE TITLE
Nicer contact searching

### ISSUE THREAD

**Issue by PantherPaulchen** [threema-ch/threema-web#208] opened 2017-05-01 11:53 UTC
## Expected Behavior

The UI should be near to the UI on mobil

## Current Behavior

When you search for another contact after you've allready typed letters, you have to use backspace many tims or Strg+a and backspace one time to clear.

## Possible Solution

In the app there is an "x" at the end that clears with one click.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Threema Web version: 1.1.0
* Threema for Android version: 3.13
* Threema for Android source: Threema Store
* Browser name and version: Firefox
* Operating system and version: Ubuntu

**Comment by dbrgn** [comment] 2017-05-01 11:55
Duplicate of #92 :)

**Closed by dbrgn** 2017-05-01 11:55 UTC
