### ISSUE TITLE
Cannot establish connection using Firefox 69.0b1

### ISSUE THREAD

**Issue by apiraino** [threema-ch/threema-web#840] opened 2019-07-05 09:55 UTC
## Bug Description

Connection establish times out on Firefox Developer Edition 69.0b1

Does not happen with Firefox stable 67.0.4 or Chromium 75.0.3770.90

## Steps to Reproduce (for bugs)

* Try to scan the QR code from an Android device

Here's some logging from the browser console. Let me know if you need more debug logging
```
[PeerConnectionHelper] Initialize WebRTC PeerConnection 
Using more than two STUN/TURN servers slows down discovery
ICE failed, add a STUN server and see about:webrtc for more details
[StatusController] Connection lost (Android). Attempting to reconnect... 
[WebClientService] Stopping (reason=stop, send=true, close=false, connectionBuildupState=n/a) 
Initializing (keyStore=yes, peerTrustedKey=yes, resume=true) 

ARIA: Attribute " aria-label ", required for accessibility, is missing on node: 
<input class="ng-pristine ng-untouched ng-valid" type="password" ...
[StatusController] Reconnect timeout 1. Retrying... 
[WebClientService] Stopping (reason=stop, send=true, close=false, connectionBuildupState=n/a) 
Initializing (keyStore=yes, peerTrustedKey=yes, resume=true) 
ARIA: Attribute " aria-label ", required for accessibility, is missing on node: 
<input class="ng-pristine ng-untouched ng-valid" type="password" ...

[StatusController] Reconnect timeout 2. Going back to initial loading screen... 
[WebClientService] Stopping (reason=error, send=false, close=welcome, connectionBuildupState=reconnect_failed) 
```

## Your Environment

```
$ uname -a
Linux 5.0.0-20-generic #21-Ubuntu SMP Mon Jun 24 09:32:09 \
    UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

* Threema Web version: Version 2.1.7 Glärnisch
* Threema App version: (Android) 3.7 Build 2000482
* Browser name and version: Firefox Developer Edition 69.0b1
* Computer operating system and version: Linux Ubunu 19.04
* Smartphone operating system and version: Android 7.something

**Comment by rugk** [comment] 2019-07-05 10:14
Duplicate of https://github.com/threema-ch/threema-web/issues/833

**Closed** 2019-07-05 11:40 UTC
Labels: bug, duplicate
