### ISSUE TITLE
Messages are sent out of order

### ISSUE THREAD

**Issue by joelfischerr** [threema-ch/threema-web#505] opened 2018-06-01 05:22 UTC
## Expected Behavior
When the connection to the phone has been reestablished, the message sent first should be sent before all other messages. I.e. sending the numbers 1 to 10 in separate messages and then sending a message with text "test" as soon as the connection is green again should result in the numbers 1 to 10 appearing on the phone (and preferrably on the phone of the contact receiving the messages) in order before the message with text "test".
This happens with this constructed example, but also frequently happens in when using Threema Web normally.

## Current Behavior
Sending the numbers 1 to 10 whithout a connection (bar is orange) and then sending a message with the text "test" as soon as the bar turns green, usually results in messages never leaving the outbox and/or the message "test" appearing on the phone before the messages containing 1 to 10.

## Possible Solution
Might be something with the outgoingMessageQueue.
_Edit:_ I have not looked at the output in the console. There might be something interesting there.

## Steps to Reproduce (for bugs)
1. Start Threema Web.
2. Force quit Threema on the phone and wait for the connection bar to turn orange.
3. Send 10 messages containing the numbers each containing one of the numbers 1 to 10 in order.
4. Prepare a message with text "test" in the new message field.
5. Launch Threema Web on the phone or wait for the connection bar to turn green
6. As soon as the bar turns green hit send to send the message with text "test"
7. "test" should appear on the phone somewhere in between the messages containing the numbers 1 to 10.

## Your Environment
* Threema Web version: 2.0.0-beta.1
* Threema App version: 4.0 (2309)
* Browser name and version: Tested with Safari 11 and Firefox 60
* Computer operating system and version: macOS 10.13
* Smartphone operating system and version: iOS 11.4

**Comment by joelfischerr** [comment] 2018-06-12 18:58
Since this was still happening in beta 5, I tried to look into it and I think I have found something.

When Threema Web is running and then the phone disconnects (I put it into airplane mode to test it), and then a message is sent in Threema Web this message will never arrive on the phone.

I have copied the logging output from line 2761 in webclient.ts in front of line 2760 [(webclient.ts Line 2760)](https://github.com/threema-ch/threema-web/commit/34ee21bda7b040094a4ff9dedf9f41097a63a822#diff-8363d34b348567f11accf4d6e712340eR2760) to check whether the message is actually added to the queue and it seems that it is not i.e. `this.salty.state !== 'task'` is false. This then causes the message to not be added to the outgoingMessageQueue and to not be sent on the next reconnect.

**Comment by dbrgn** [comment] 2018-06-14 14:02
@joelfischerr thanks for the debugging, you were right!

Normally if the connection is lost, this happens because the app is stopped in the background. In that case the socket is properly closed and Threema Web immediately notices that the connection is gone.

However, if you put the phone in airplane mode, the socket won't be closed by the OS. Instead, because this is a TCP connection, Threema Web won't notice the connection loss until a packet is sent again (without a response).

To avoid this, there is a WebSocket ping message that is sent every 30 seconds (we will reduce that to 20s in the next version). When the ping message is sent, the server will notice that the smartphone is gone and will notify Threema Web.

The problem is that the SaltyRTC server does not send a send-error message in this case, so we can't know whether a message was delivered or not. @lgrahl is that a bug?

Using the send-error message, it should be possible to determine which message was lost, and to put that message in the queue again.

**Comment by joelfischerr** [comment] 2018-06-15 18:52
> Using the send-error message, it should be possible to determine which message was lost, and to put that message in the queue again.

Wouldn't that cause the messages to arrive on the phone in the wrong order?

**Comment by dbrgn** [comment] 2018-07-04 15:43
@joelfischerr nobody said that a queue is not sorted.

@lgrahl I think it would be best to check whether we could use the sequence number of the message in order to implement a sorted queue that sorts a message on insertion.

**Comment by joelfischerr** [comment] 2018-07-05 14:16
I thought that a message 2 could be sent before the loss of message 1 was noticed. Then message 1 would be in the correct position in the queue, but would still arrive in the wrong position on the phone.

**Comment by joelfischerr** [comment] 2018-07-05 14:32
Thanks for the explanation.

**Comment by lgrahl** [comment] 2018-07-09 17:01
This cannot be fixed without some acknowledgement protocol. See https://github.com/saltyrtc/saltyrtc-server-python/issues/77#issuecomment-403548130.

**Comment by ovalseven8** [comment] 2018-09-08 07:38
Will this be fixed before the iOS release?

**Comment by lgrahl** [comment] 2018-09-08 09:52
^

**Comment by dbrgn** [comment] 2018-09-17 15:27
Fixed by #551.

**Closed by dbrgn** 2018-09-17 15:27 UTC
Labels: bug, os-ios

**Comment by lgrahl** [comment] 2018-09-17 21:15
(Would have been closed with an eventual merge to master)
