### ISSUE TITLE
Chats scrolls down when trying to scroll up and older content loads in

### ISSUE THREAD

**Issue by NicolasGoeddel** [threema-ch/threema-web#1153] opened 2022-10-28 09:51 UTC
## Bug Description
When I scroll up to see older messages in a chat and I reach the point where older content has to be loaded in, then the content scrolls back to the point where I started scrolling. This is really annoying. It should just keep its scroll position or else I lose focus.

## Steps to Reproduce (for bugs)

1. Open a longer chat dialog or a group chat.
2. Use your mouse wheel to scroll up to the point where the loading icon appears.
3. Wait until it has loaded.
4. Now you should be at the point again where you started scrolling.

## Your Environment

* Threema Web version: 2.4.4
* Threema App version: 4.84 Build 3000761 Google Play
* Browser name and version: Firefox 106.0.2 (64-Bit)
* Computer operating system and version: Ubuntu 22.04 Gnome
* Smartphone operating system and version: Android 13

**Comment by lgrahl** [comment] 2022-10-28 10:18
Thanks for the report. This is a duplicate of #277. We're focusing our resources to work on a successor to Threema Web (and Desktop). This is one of the issues we won't address this in the current version anymore.

**Closed by lgrahl** 2022-10-28 10:18 UTC
Labels: bug, awaiting triage

**Comment by NicolasGoeddel** [comment] 2022-10-28 10:22
> Thanks for the report. This is a duplicate of #277. We're focusing our resources to work on a successor to Threema Web (and Desktop). This is one of the issues we won't address this in the current version anymore.

Thanks for your reply. Where can this successor be tracked? Is there a milestone or a projects page to see the progress? Or is this a completely new repository?

**Comment by lgrahl** [comment] 2022-10-28 10:32
It is the [Threema 2.0 for desktop project](https://twitter.com/ThreemaApp/status/1476490273119252480) which is not on GH atm. There might be news soon™.
