### ISSUE TITLE
Heavy battery drain

### ISSUE THREAD

**Issue by Johnnii360** [threema-ch/threema-web#566] opened 2018-08-15 08:04 UTC
## Expected Behavior
Low battery consumption like What's App Web.

## Current Behavior
Drains much of battery life on Samsung Galaxy Note 8 (SM-N950F). 3% within 30 Minutes!

## Possible Solution
n/a

## Steps to Reproduce (for bugs)
None available.

## Your Environment
* Threema Web version: 2.0.2
* Threema App version: 3.51.2000430 Google Play
* Browser name and version: Google Chrome 66.0.3359.139
* Computer operating system and version: Microsoft Windows 10 Pro & Enterprise Build 1803
* Smartphone operating system and version: Android 8.0.0, Kernel 4.4.111-13688770-QB19092629

**Comment by dbrgn** [comment] 2018-08-15 08:05
This is a duplicate of #60. Closing in favor of the other issue :)

**Closed by dbrgn** 2018-08-15 08:05 UTC
