### ISSUE TITLE
Chat list shows old messages instead of most recent ones

### ISSUE THREAD

**Issue by uwemock** [threema-ch/threema-web#825] opened 2019-06-27 08:43 UTC
## Bug Description

The chat list on the left hand side should display the most recent messages in each chat, together with the date and time that message has been received. This is not the case. The following screenshot shows Threema Web opened at 2019-06-27, 10:15. 

![2019-06-27_threema_web](https://user-images.githubusercontent.com/31033449/60250172-66f83580-98c6-11e9-974d-264b1abe0cc1.png)

The first two entries are the same as on my mobile device, except that the most recent messages should bear the date "27. Jun." (in both cases).

The third entry in Threema Web is on position four on my mobile device, date and time are correct. From this position, all dates and times are correct.

The chat that appears third on my mobile device is completely missing in Threema Web.

Force-stopping Threema on my mobile device and restarting it together with the Threema Web session resolved the problem. This also reliably resolves the problem of Threema (on the mobile device) showing wrong message status in the chat list on the mobile device (Threema issue #538400), so these two problems might be related.

## Steps to Reproduce (for bugs)

1. Open Threema Web.
2. Compare the chat list in Threema Web with the chat list on your mobile device.

## Your Environment

* Threema Web version: 2.1.7
* Threema App version: Android 3.7 Build 2000482
* Browser name and version: Chromium (using nativefier)
* Computer operating system and version: Kubuntu 18.04.2
* Smartphone operating system and version: Android 6.0.1

**Comment by dbrgn** [comment] 2019-07-02 08:42
Is this reproducible, or did it just happen once?

Did you have the "Debug Log" (used to be called "Message Log") enabled when this happened?

**Comment by uwemock** [comment] 2019-07-02 09:26
The thing I described above happened just once.

As I stated above, I suspect this to be related to a bug in the Threema Android app (Threema issue #538400). This issue is about the chat list in the Android app showing an outdated message status (e.g. "outgoing" or "inbox"; when I open the chat, the status has already changed to "read"). I have this every now and then, without an obvious cause. The next tie this happens, I will check if the above bug in Threema Web also reappears.

**Comment by dbrgn** [comment] 2019-07-03 08:06
If the issue with the missing messages happens again, please send a debug log (Settings > Troubleshooting > Message Log) to the support team and mention this GitHub issue.

Regarding the status that isn't updated: I think that's the same issue as #527. We already have a solution for that on the app side, but it isn't fully implemented yet.

I'll close this issue for now since we don't have any information available to debug the missing messages in the conversation overview.

**Closed by dbrgn** 2019-07-03 08:06 UTC
Labels: bug
